### ISSUE TITLE
how can i use xgboost in c++ project

### ISSUE THREAD

**Issue by lwang1108** [dmlc/xgboost#1016]
how can i use xgboost in c++ project?

**Comment by barbara73** [comment]
Yes, I would like to know this as well. Since it is written in C++ it should be not too difficult!!?

**Comment by thirdwing** [comment]
Please take a look at https://github.com/dmlc/xgboost/blob/master/src/cli_main.cc

This can be used as a starting point for your C++ project.

**Comment by barbara73** [comment]
thank you. but it gives this error, when i try to compile cli_main.cc:

src/cli_main.cc:165:19: error: no member named 'emplace_back' in
      'std::__1::vector<std::__1::unique_ptr<xgboost::DMatrix,
      std::__1::default_delete<xgboost::DMatrix> >,
      std::__1::allocator<std::__1::unique_ptr<xgboost::DMatrix,
      std::__1::default_delete<xgboost::DMatrix> > > >'
            deval.emplace_back(
            ~~~~~ ^
src/cli_main.cc:271:58: error: expected expression
        std::unique_ptr<Learner> learner(Learner::Create({}));
                                                         ^
src/cli_main.cc:297:58: error: expected expression
        std::unique_ptr<Learner> learner(Learner::Create({}));
                                                         ^
src/cli_main.cc:313:22: warning: range-based for loop is a C++11 extension
      [-Wc++11-extensions]
        for (float p : preds) {
                     ^
5 warnings and 3 errors generated.


can you tell me, how to fix it?

**Comment by drag0** [comment]
I trained XGBoost model with Python and then generated C++ code from XGBoost's raw model dump. Here is my code: https://github.com/drag0/xgb2cpp

**Comment by HackInvent** [comment]
I still don't undestand why XGBoost is only oriented to Python, R, Scala,..etc without any complete tutorial with C++

**Comment by headupinclouds** [comment]
FWIW, I posted a small working example based on a previous C++ use case here:
https://github.com/dmlc/xgboost/issues/2262#issuecomment-299709516

**Comment by khotilov** [comment]
@HackInvent The CLI code is sort of a "guide" of how to access the xgboost API from C++. Other than that, all you need to do is to use the includes from `include/`, `dmlc-core/include/` and `rabit/include/`, and to link to the xgboost library. The specifics on how to integrate it into your project, using what toolchain, etc. all that would be highly dependent on your particular needs and circumstances.

**Comment by HackInvent** [comment]
Thank you, it would be great if at least we have a small documented usecase to start using XGBoost with C++ based on Linux/Cygwin style gcc toolchain.
I will try it when I finish making things compiling.
Thank you again.

**Comment by HackInvent** [comment]
@headupinclouds why didn't you use the same format of train/test files like in your code example? further more I could find any example of .pba.z/*.cpb model.
Do you have a set of workding train/test/model files?

**Comment by headupinclouds** [comment]
@HackInvent 

> why didn't you use the same format of train/test files like in your code example?

I'm not sure quite what you mean.  I adapted this sample from another project to support reuse in a few projects, and since the C++ question comes up fairly often, I put it on github.  I will likely extend this for future projects, but as @khotilov mentions, such xgboost wrappers are likely to be fairly application specific.  This is tailored primarily towards running pre-trained regression models (pose regression, etc) on mobile devices with bare bones portable model files, but might also be useful to demonstrate the xgboost CLI.  The code includes a small [sample console app](https://github.com/elucideye/xgboostcpp/blob/master/src/test/test-xgbooster.cpp#L14) for working with simple CSV file input, as well as a small GTest based [unit test](https://github.com/elucideye/xgboostcpp/blob/master/src/lib/xgboostcpp/ut/test-xgboostcpp-regression.cpp) based on a "Boston Housing" regression problem in sklearn.  It reproduces this small sample: http://scikit-learn.org/stable/auto_examples/ensemble/plot_gradient_boosting_regression.html with favorable results.

> further more I could find any example of .pba.z/*.cpb model.

There are two archive formats that can be used: (1) `*.cpb` a cereal portable binary archive format (preferred); and (2) `*.pba.z` a boost portable binary archive format with boost iostream compression.  I had been using boost serialization initially, and have since started using cereal as an alternative, since the lightweight header only design is very convenient for this type of application.

> Do you have a set of workding train/test/model files?

The "Boston Housing" unit test is probably easiest to use.  For convenience, the input training data and ground truth is included directly in the compiled executable via c++ files.   You can take a look in the Travis + Appveyor configuration files to see examples of this running with different toolchains (pick one closest to what you need): https://github.com/elucideye/xgboostcpp/blob/master/.travis.yml (just add `--test` to the sample build command shown in the README).

```
# replace xcode with your preferred toolchain
polly.py --toolchain xcode --install --reconfig --verbose --test --open
```

I hope that helps.  If you have further questions about that sample code (not directly related to xgboost), it is probably better to follow up offline in that project directly.  If there is general interest in the [cereal](https://github.com/USCiLab/cereal) serialization (header only C++11 lib), I'd be happy to work on a PR.

**Comment by HackInvent** [comment]
@headupinclouds thank you for the details
I finally succeeded to import your code into QtCreator
There where a small issue in test-xgboostcpp/load_csv: x.resize(x.size()); to be replaced by-> y.resize(x.size());
The model is correctly saved into cpb after training with a csv sample
But when I run the test without (-t) no output is coming, except a file called featmap.txt.
I will get some doc arround to check how to use it properly,
Thanks

**Comment by HackInvent** [comment]
@headupinclouds I succeeded to run an example to predict a simple f(x)=x² function using the gblinear booster with your code on the QtCreator integration.
Next step will be a more complex example with GPU updater=grow_gpu.
As soon as I complete the integration with Qt Framework I will push it the GitHub.

**Comment by headupinclouds** [comment]
Sounds good.  Thanks for the fix.  Feel free to send a patch.  I can add a small test for the CLI application (similar to the unit test) to make sure that is behaving well.  BTW, this is using a modified xgboost lib (fork of v0.40) which I don't believe has the GPU additions.  The mobile serialization features required intrusive mods (cereal portable binary archive, half precision floating point, skipping unrequired fields for prediction).  It is a fairly specific use case, and I don't know if you need any of that stuff.  If you use the standard serialization read/write calls [here](https://github.com/elucideye/xgboostcpp/blob/master/src/lib/xgboostcpp/XGBooster.h#L50-L51), it should be pretty easy to adapt the wrapper to the latest xgboost release.  I can also help update the xgboost version in the hunter at some point.  It may be better to migrate discussion regarding the wrapper/interface to that project.  If there is a general need for an additional C++ integration layer, we should discuss further and try to contribute it upstream.  I haven't looked at the current API for a while, so I would have to catch up on the current API first.
