### ISSUE TITLE
xgboost v2.1.0 is incompatible with pandas<1.2

### ISSUE THREAD

**Issue by winwinashwin** [dmlc/xgboost#10471]
To Reproduce
---

```python
import xgboost as xgb
import pandas as pd

X = xgb.DMatrix(pd.DataFrame({"a": [1, 2], "b": [2, 4]}), label=[0, 1])
```

xgboost==2.1.0, pandas==1.1.5    ---> FAIL
xgboost==2.0.3, pandas==1.1.5    ---> PASS
xgboost==2.1.0, pandas==1.2.0    ---> PASS

---

There is no version constraint specified in `pyproject.toml` for pandas optional dependency.

The `Float32Dtype` used here is only available in pandas v1.2+

https://github.com/dmlc/xgboost/blob/213ebf7796b757448dfa2cfba532074696fa1524/python-package/xgboost/data.py#L476

**Comment by trivialfis** [comment]
At the moment, we are not very good at keeping track of these input versions and the policy is always testing with the latest for optional dependencies (pandas is not required to run xgboost). Otherwise, the constraint solver will run into trouble with the amount of input types https://github.com/dmlc/xgboost/blob/master/doc/python/python_intro.rst#support-matrix .

**Comment by trivialfis** [comment]
Hopefully, https://github.com/dmlc/xgboost/issues/10452 can help in the future.

**Comment by hcho3** [comment]
For now, let's require Pandas 1.2+. I submitted #10476
