### ISSUE TITLE
Add Out-of-Bag performance validation

### ISSUE THREAD

**Issue by hetong007** [dmlc/xgboost#1070]
Since we have the parameter `subsample`, it is natural to perform out-of-bag evaluation for each tree. This can be a faster and simpler substitution of cross validation on some large input. As noted below, it is maily useful when `num_parallel_tree` is presented.

The current subsampling process is done in C++, therefore we might need to predict and evaluate on the C++ side if oob-validation is requested.

**Comment by khotilov** [comment]
Because boosted trees are correlated, OOB evaluation is a rather handicapped concept and it is not so natural as in random forests. Here we can only look at overall "OOB improvements" brought by each new tree. That metric usually leads to underestimates in optimal number of iterations (sometimes by a lot), and it's hard to say how reliable it might be for optimizing the other parameters in xgboost. So I don't have high hopes.

However, an OOB evaluation option could be rather useful for the "random forest" setting.

**Comment by hetong007** [comment]
@khotilov that's a good point. The oob data points for one tree could be actually included in the previous trees, thus they are not truely "out".

I would like to have it mainly for the random forest version.
