### ISSUE TITLE
xgboost and its sklearn's integration feature_importances_ error

### ISSUE THREAD

**Issue by guiem** [dmlc/xgboost#1082]
reported the behaviour at stackoverflow: http://stackoverflow.com/questions/36216986/xgboost-and-its-sklearns-integration-feature-importances-error

**Comment by thusithaC** [comment]
Any luck with this?

**Comment by flacjacket** [comment]
I'm going to guess you are using pandas dataframes? Because you don't instantiate the DMatrix used to train the XGBClassifier, if you use X/y data that doesn't have feature names, e.g. a numpy ndarray, the DMatrix defaults to using `fn` for the nth feature. In that case, the logic in `feature_names_` works.

**Comment by guiem** [comment]
@flacjacket correct! I was using a pandas dataframe. 
Anyway, what you imply? Should I feed a DMatrix to the 'fit' function of the classifier? Bear in mind that I'm using the XGBClassifier wrapper for sklearn, so when I try to pass the data as a DMatrix sklearns interface complains about DMatrix not having attribute 'shape'.
I might be missing something though, any help is going to be much appreciated! :)
