### ISSUE TITLE
Two slightly different tarballs generated in release script; differentiate them

### ISSUE THREAD

**Issue by jakirkham** [dmlc/xgboost#11045]
From @hcho3 in https://github.com/conda-forge/xgboost-feedstock/pull/203#discussion_r1860210736 :

> It looks like we generate two different files with the same name `xgboost-2.1.3.tar.gz` from [this script](https://github.com/dmlc/xgboost/blob/master/dev/release-artifacts.py). This is super confusing and we should remove one of them.

<hr>

After further discussion below, it appears both are needed for two different purposes. So we decided to name them differently

**Comment by trivialfis** [comment]
One is in the `dist` directory for Python sdist, the other one is in the root output directory for the general source package. Yeah, naming is hard.

**Comment by jakirkham** [comment]
Ok then think we need to be more careful about which one gets uploaded where

Think the GitHub release archive used the `sdist` for 2.1.2 whereas 2.1.3 used the general source package

How is this upload process typically handled?

**Comment by trivialfis** [comment]
@jakirkham The `dist/xgboost-2.1.3.tar.gz` is uploaded to PyPI for the Python release, while the general one is uploaded to the GitHub release page for others who have their distribution mechanism.

**Comment by trivialfis** [comment]
No, it's mostly a manual process. The packages are generated by the script you referenced, then I will upload the Python packages with my private key, and upload to the GitHub package when making a release.

It's not easy to automate the Python package release since we might run into issues like PyPI storage capacity. As for the GitHub package, we need to write the release note and git tags manually, which cannot be fully automated.

**Comment by trivialfis** [comment]
Sounds good to me

**Comment by trivialfis** [comment]
Opened a PR: https://github.com/dmlc/xgboost/pull/11055 . cc @hcho3 .

**Comment by jakirkham** [comment]
Edited the issue to reflect this updated understanding of the issue and resolution
