### ISSUE TITLE
CMake and CPU instructions docs

### ISSUE THREAD

**Issue by david-cortes** [dmlc/xgboost#11121]
The instructions for building the R package from source here:
https://xgboost.readthedocs.io/en/latest/build.html#building-r-package-from-source
.. mention:
> But if you want to use CMake build for better performance (which has the logic for detecting available CPU instructions)

In the CMake file, I only see a deprecated "USE_AVX" option, which doesn't modify the resulting build:
https://github.com/dmlc/xgboost/blob/2d1c26b38a0a48f0d719783dc216f942ca9c41ee/CMakeLists.txt#L173

What is this CPU intruction detection feature? As far as I am aware, XGBoost doesn't have code paths for different instruction levels, or does it? Are these docs outdated?

**Comment by trivialfis** [comment]
https://github.com/dmlc/xgboost/blob/master/cmake/PrefetchIntrinsics.cmake

**Comment by david-cortes** [comment]
Thanks. Couple questions:

* Wouldn't a check of the form "test that it compiles" without "test that it runs" potentially cause it to generate artifacts that are not usable for some platforms?
* For the R package in specific, why is this check done only in the cmake build and not in the regular CRAN build? Did it trigger errors at CRAN?

**Comment by trivialfis** [comment]
- That can happen, for instance, apple silicon x86->arm translation couldn't handle this. But other than that, we are using sse2, which should be quite safe.
- Because no one is motivated enough to work with autotools yet ... I'm sure R has good reasons to continue its use, but so far I haven't met anyone who is keen on working with it. I myself really want to replace it when possible.
