### ISSUE TITLE
xgboost saving (into textfile and binary) and then loading from xgb and then saving to text) not identical

### ISSUE THREAD

**Issue by ydalal** [dmlc/xgboost#1205]
Hi,
I am trying to use xgboost text files to score my data in java. I save the trained model x in 2 type of files first dump_model and second using save_model. When i load the second type of file into python and save using dump_model again, i see there are differences in definition. I have attached 2 text files, **xgb.model.orig.txt** is the file saved using original model and **xgb.model.txt** is the file saved from binary loaded into python. There are minute differences in nodesplit values, ex. there is +-0.5 values appended to split value. Please let me know if it's a known bug, i have attached the code below and xgboost model definitions, for this issue.

Please find my code to train a sample model and then save it into binary and text formats,

```
import pandas as pd
import xgboost as xgb
import numpy as np
from time import gmtime, strftime

hadoop_xgboost_scoring_path="/Users/ydalal/hadoop_xgboost_scoring"
run_id=strftime("%Y%m%d-%H%M%S", gmtime())

#   GENERATE RANDOM TRAINING DATA
min_val=1
max_val=100
df = pd.DataFrame(np.random.randint(min_val,max_val,size=(1000, 10)), 
                  columns=['fname1','fname2','fname3','fname4','fname5','fname6','fname7','fname8','fname9','fname10'])
dtrain = xgb.DMatrix( df.ix[1:500,:], label=pd.DataFrame(np.random.randint(2, size=500))) # First 500 records for training
dtest = xgb.DMatrix( df.ix[501:,:], label=pd.DataFrame(np.random.randint(2, size=499))) # Rest record for tuning
#   Train the xgb model
num_round = 40
max_depth=4
param = {'bst:max_depth':max_depth, 'bst:eta':1, 'silent':1, 'objective':'binary:logistic'}
param['nthread'] = 4
#param['eval_metric'] = 'logloss'
plst = param.items()
evallist  = [(dtest,'eval'), (dtrain,'train')]
bst = xgb.train( plst, dtrain, num_round, evallist)

#   Save the xgb model
model_output=hadoop_xgboost_scoring_path+"/resources/%s%s"%(run_id,".xgb.model.txt")
print(" Saving model to , %s"%(model_output))
bst.dump_model(model_output)
bst.save_model(model_output.replace("txt","xgb"))

#   Generate Validation data
dvalidation= pd.DataFrame(np.random.randint(0,100,size=(10000, 10)), columns=['fname1','fname2','fname3','fname4','fname5','fname6','fname7','fname8','fname9','fname10'])
dval_output=hadoop_xgboost_scoring_path+"/resources/%s%s"%(run_id,".xgb.valdata.txt")
print("Saving validation data to, %s"%(dval_output))
dvalidation.to_csv(dval_output,index=False)

#   Score Validation data
scores=pd.DataFrame(bst.predict(xgb.DMatrix(dvalidation),output_margin=False,ntree_limit=0))
dval_scores_output=hadoop_xgboost_scoring_path+"/resources/%s%s"%(run_id,".xgb.valdata.scores.txt")
print("Saving validation data scores to, %s"%(dval_scores_output))
scores.to_csv(dval_scores_output,index=False)

#   Information 
print("\n\n\n\tThis run generated following files : \n\tRunId- %s\n\t%s\n\t%s\n\t%s\n\t%s"%(run_id,model_output,dval_output,dval_scores_output,model_output.replace("txt","xgb")))

```

[20160517-022638.xgb.model.txt](https://github.com/dmlc/xgboost/files/267321/20160517-022638.xgb.model.txt)
[20160517-022638.xgb.model.orig.txt](https://github.com/dmlc/xgboost/files/267322/20160517-022638.xgb.model.orig.txt)

**Comment by khotilov** [comment]
You see such differences b/c first you dump & save a Booster which contains non-float feature_types (you have int features), and then, I guess, you load it into a new Booster without making it aware of the feature types. However, the save_model/load_model methods don't serialize feature types. When feature types are known to a Booster, its dump_model method would result in integer features printed in a special way:
https://github.com/dmlc/xgboost/blob/51154f42fe0c09c9597b639d086f69cdaa5c6fa8/src/tree/tree_model.cc#L46
When no feature names/types are stored, dump_model would dump the splits as floats with the standard float printout precision.

A good and simple approach is to always use float features. Otherwise, if you save a model with different feature types, then it's better to make sure to restore the types too. You can do it either by passing a dataset of the same types via the `cache=` parameter to `Booster()` when loading a model, or by explicitly setting the feature_names and feature_types properties before running the `dump_model` again.

**Comment by ydalal** [comment]
Thanks Vadim,
It works with float features.
