### ISSUE TITLE
plot_importance in Python

### ISSUE THREAD

**Issue by FaguiCurtain** [dmlc/xgboost#1245]
I've posted my issue here but no one could help me

https://stats.stackexchange.com/questions/213782/xgboost-on-python-plot-performance

following the instructions from https://xgboost.readthedocs.io/en/latest/python/python_intro.html

after building my model, i tried on Jupyter (using Mac OS X, Chrome browser)

```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
plt.style.use('ggplot') 
xgb.plot_importance(bst) 
xgb.plot_tree(bst, num_trees=2) 
xgb.to_graphviz(bst, num_trees=2)
```

but i have some problems: the to_graphviz does return me a plot, but its too big, and i can't see it whole. Its cut on the right side

the first two commands (if i put a # in front of the last line) don't show any plot at all. is there something like a.show() missing ?

Instead i get the following output

> "matplotlib.axes._subplots.AxesSubplot at 0x12f0ee7d0" (between <>)

can anyone help ? thank you

**Comment by krishnateja614** [comment]
I got the same issue. My model has number of estimators equal to 300 and the plot of the tree is too big. Also, do you know how to interpret the tree,like for a new example can you see which class would it end up on by tracking the tree. The trees leaves just contain a score instead of a label. Do you know how to interpret the score or what that means.

**Comment by sinhrks** [comment]
You must call `plt.show()` to display the plot because sometimes we don't want to (save figure silently, etc).

The behavior is common in popular python packages like seaborn and pandas.
