### ISSUE TITLE
Will the feature order affect the result of XGBoost?

### ISSUE THREAD

**Issue by litoeknee** [dmlc/xgboost#1256]
HI,

If we fix all the other parameters, just change the order of features in libsvm.

Will it affect the final result? And the importance of each feature?

Thank you!

**Comment by pommedeterresautee** [comment]
In theory it has no effect. But according to another issue posted here, there is a small effect.

**Comment by tqchen** [comment]
This only affects when there are ties, i.e. when the two features have same gain during split, in which case the first feature will be preferred

**Comment by litoeknee** [comment]
@tqchen 
Thank you for your response!

in that case, how can we recognize the importance of each feature? Apart from the get
_fscore function provided?

We have used this function to check the importance of each feature but when we change the order the result shows some differences.

Will the parameters setting affect the importance ranking? Such as overfitting?

Thank you!

**Comment by litoeknee** [comment]
@pommedeterresautee 
Thank you for your response!

It seems I can't find the related issues at this time... Could you kindly post the link here?

Thank you!

**Comment by pommedeterresautee** [comment]
For the link I will check later, I am at work right now. 

For you question about importance feature ranking, of course settings have an impact. For instance, think to column subsampling, it will have a direct impact on the number of times a feature is selected and its importance in the model (and its final ranking at the whole model scale). 

Regarding the other parameters, they will also have an impact. The reason is that boosting is sequential (unlike random forest for instance) therefore if the first tree is built one way with specific features (because of the parameters), it will impact the following trees and the features they use. Regarding obtaining the feature importances, I don't know well the Python API, but you can parse yourself a dump of the model if what you are looking for doesn't exist yet.

Kind regards,
Michaël
