### ISSUE TITLE
R interface uses stringr CRAN package which is GPL-2 licensed, incompatible with Apache 2.0 

### ISSUE THREAD

**Issue by rbalint** [dmlc/xgboost#1333]
Probably the most viable fix would be using stringi package functions instead of the wrappers in stringr.

https://github.com/dmlc/xgboost/blob/master/R-package/NAMESPACE
https://cran.r-project.org/web/packages/stringr/index.html
http://www.apache.org/licenses/GPL-compatibility.html

**Comment by tqchen** [comment]
cc @hetong007

**Comment by hetong007** [comment]
Hi @rbalint, there is a vote in https://github.com/dmlc/xgboost/issues/1338 about the licensing issue. 

It is because `ggplot2`, `knitr`, `data.table` are also GPL, and the cost to keep xgboost from them is high.

**Comment by tqchen** [comment]
as a correction, only ```ggplot2``` and ```stringr`` will become problem

**Comment by pommedeterresautee** [comment]
I have checked a legal books about GPL (unfortunately it s in French: Droit des logiciels - édition Puf - F Pellegrini et S. Canevet) and basically, to avoid contamination of a project with GPL2 licence, you need to wrap the GPL2 code and access to it through a generic interface.

This interface should make it possible to use code from other projects with similar functionalities than the GPL code. One interesting point is that to make it work, another project with similar function but under another licence should exist. 

The implementation of the other project has not to be written, but just be **easily** possible. The idea is that it should be easy to replace the code under GPL with another one because of the interface (like a lego block). 

The approach is inspired of how to limit GPL2 contamination because of the Linux kernel executing some non GPL code.

In general, my opinion is to limit the consequences of GPL code to the final user. 
For instance, forcing the user to install another package to get some functions just for legal reasons is really an overkill. And letting the GPL licence contamining the whole project and making it impossible to use for some startup seems not Ok at all.

If you have any question, please don't hesitate.

Kind regards,
Michaël

**Comment by pommedeterresautee** [comment]
`stringr` is not used anymore.
https://github.com/dmlc/xgboost/pull/1401

I close the issue.
