### ISSUE TITLE
does nthread works in predict()?

### ISSUE THREAD

**Issue by cnglen** [dmlc/xgboost#1345]
Assuming:
- the model is trained using nthread=32
- and the model is saved

When call predict() using the saved model, does the nthread(32 set in train()) still works?
- answer in R API?
- answer in Python API?

**Comment by rfcv** [comment]
In R API I have noticed that it uses the same number of threads that were used to fit the model. Thus, if you want to use more or less threads for prediction than what was used to fit the model, you cannot, as there is no `nthread` parameter for `predict` like there is for `xgboost`

**Comment by khotilov** [comment]
When a model is used for prediction in the same session/process where it was trained, by default it would use the same number of threads as was used last time for fitting.

When a saved model is loaded in a new session where no training with `nthread` parameter was run, the model would by default use all the available threads (as if nthread=0), provided that  `OMP_NUM_THREADS` environment variable wasn't set.

The number of threads to use for prediction could always be controlled by setting the `nthread` parameter before calling `predict`, e.g.:
- R: `xgb.parameters(bst) <- list(nthread = 1)`
- python: `bst.set_param('nthread', 1)`

In some situation it might be more convenient to control the number of threads by defining an `OMP_NUM_THREADS` environment variable: https://gcc.gnu.org/onlinedocs/libgomp/Environment-Variables.html

There is a quirk: `nthread` currently works as intended only with the `gbtree` (or `dart`) booster. It seems to be so because `omp_set_num_threads` is only called in `GBTree::Configure`:  https://github.com/dmlc/xgboost/blob/7cfeb5f0122e76de3581cdcb542dcf2b9202aae9/src/gbm/gbtree.cc#L149 . For `gblinear`, if nthread wasn't limited earlier (either by env-var or by training a gbtree model), it would use all the available system threads for training (which might make the training slower), and it has no parallelization for prediction.

**Comment by yangl326-Dylan** [comment]
i use python to train model, and using the model in c++.  Setting "nthread":1 when training is not effected in predict.  need to use XGBoosterSetParam() function explicitly.
