### ISSUE TITLE
DART ntreelimit [predict]

### ISSUE THREAD

**Issue by LinearLarryXTX** [dmlc/xgboost#1426]
Trying to use ntreelimit within predict using the DART booster but it doesnt seem recognise this parameter (unlike the gbtree booster). That is, for any single model setting ntreelimit to any value gives identical results. Any ideas?

**Comment by marugari** [comment]
DART booster does not support early stopping.
If ntree_limit > 0 then `predict` returns sum of leaf scores of all exsiting trees.

**Comment by LinearLarryXTX** [comment]
Thanks for the reply. Is there any particular reason for not supporting early stopping? I looked through the code and I can't see why DART wouldn't work with this case? It's quite a useful feature of gbtree predict so I'd like to get your opinion on why it wasn't included first before attempting to add it myself.

**Comment by marugari** [comment]
New tree and dropped trees have similar prediction, so in order to adjust this overlapping leaf scores of dropped trees are modified at the same time when new tree are combined.
DART booster has keep only current leaf scores, therefore we cannot get scores as of earlier iteration after later iteration has finished.
