### ISSUE TITLE
Not possible to save and load count::poisson model from python

### ISSUE THREAD

**Issue by jansoe** [dmlc/xgboost#1474]
when i try to save and reload model

bst.save_model(filename)
bst =  xg.Booster(model_file = filename)

i get the error `XGBoostError: Required parameter max_delta_step of float is not presented.`

The same Error does not occur when I use a reg::linear model for example

the error is easily reproduced if one changes this example https://github.com/dmlc/xgboost/blob/master/demo/guide-python/basic_walkthrough.py#L13 the objective to `count::poisson`

**Comment by tonydifranco** [comment]
I get the same issue when saving/loading in R... @yangs16 do you know why this is happening?

**Comment by tonydifranco** [comment]
@yangs16 @tqchen  don't know if this is the best way to fix the problem but if you set a default in [line 153  of src/objective/regression_obj.cc](https://github.com/dmlc/xgboost/blob/master/src/objective/regression_obj.cc#L153) this won't throw the dmlc missing required parameter exception... for example, since 0.7 is the recommended value, I just did the following:

`DMLC_DECLARE_FIELD(max_delta_step).set_lower_bound(0.0f).set_default(0.7f)
        .describe("Maximum delta step we allow each weight estimation to be." \
                  " This parameter is required for possion regression.");`

I think the bigger issue is within the c_api.cc that R and Python use... I hope this gets fixed soon.  Thanks for your work to add poisson and gamma regression... maybe I can help with tweedie sometime soon.

**Comment by yangs16** [comment]
@jansoe I sent a pull request to fix the issue. You can find it at https://github.com/dmlc/xgboost/pull/1615.

**Comment by yangs16** [comment]
The fix failed the training continuation test: xgboost/tests/python/test_training_continuation.py. I think the right way is to specify the params parameter when constructing the Booster object. For example:

bst = xgb.Booster(params={'max_delta_step':'0.7'}, model_file=filename)

This will solve the crash problem.

**Comment by yangs16** [comment]
Note that the problem with the model loading was fixed. For prediction, you still need to specify the params parameter when constructing the Booster object:

params={'max_delta_step':'0.7'}
bst = xgb.Booster(params, model_file=filename)

or set the params parameter before calling the predict method:
bst = xgb.Booster(model_file=filename)
bst.set_param(params)
bst.predict(dtest)

**Comment by jansoe** [comment]
thanx for clarifying

**Comment by xelibrion** [comment]
@yangs16 I experienced this issue today, despite the fact code for loading booster from file was as above
