### ISSUE TITLE
Compilation fail

### ISSUE THREAD

**Issue by pommedeterresautee** [dmlc/xgboost#174]
Disclaimer: What I show below has only been tried on Ubuntu

When I do make Rpack, I notice:
```
...
Maintainer: ‘Tong He <hetong007@gmail.com>’
* checking package namespace information ... OK
* checking package dependencies ... NOTE
  No repository set, so cyclic dependency check skipped
* checking if this is a source package ... NOTE
Found the following apparent object files/libraries:
  src/src/gbm/gbm.o src/src/io/io.o src/src/tree/updater.o
  src/subtree/rabit/src/engine_empty.o src/wrapper/xgboost_wrapper.o
Object files/libraries should not be included in a source package.
* checking if there is a namespace ... OK
...
```

Was not a big deal for me because it finishes the process, it is just a Warning.

For the first time, instead of stupidly clicking build & reload button in RStudio to compile the package, I tried the command dev::build() from devtools package.

I got:
```
> devtools::build()
'/usr/lib/R/bin/R' --vanilla CMD build '/home/geantvert/workspace/xgboost/R-package' --no-resave-data --no-manual 

* checking for file ‘/home/geantvert/workspace/xgboost/R-package/DESCRIPTION’ ... OK
* preparing ‘xgboost’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
      -----------------------------------
* installing *source* package ‘xgboost’ ...
** libs
g++ -I/usr/share/R/include -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I../../    -fopenmp -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c xgboost_R.cpp -o xgboost_R.o
xgboost_R.cpp:7:37: fatal error: wrapper/xgboost_wrapper.h: Aucun fichier ou dossier de ce type
 #include "wrapper/xgboost_wrapper.h"
                                     ^
compilation terminated.
/usr/lib/R/etc/Makeconf:142: recipe for target 'xgboost_R.o' failed
make: *** [xgboost_R.o] Error 1
ERROR: compilation failed for package ‘xgboost’
* removing ‘/tmp/Rtmpg2lFjw/Rinst24e974ab8766/xgboost’
      -----------------------------------
ERROR: package installation failed
Erreur : Command failed (1)
> 
```

I noticed that it is the same guy in both story (xgboost_wrapper).

I can still compile the package with Rstudio button, but may be there is a bug in installation script.

FYI information, I tried the command because it is supposed to generate the Vignettes and install the compiled version of the source code.

**Comment by pommedeterresautee** [comment]
Under Windows, same issue

```
> dev::build()
Error in loadNamespace(name) : aucun package nommé ‘dev’ n'est trouvé
> build()
"C:/PROGRA~1/R/R-31~1.2/bin/x64/R" --vanilla CMD build  \
  "C:\Users\mbenesty\Documents\GitHub\xgboost\R-package" --no-resave-data --no-manual 

* checking for file 'C:\Users\mbenesty\Documents\GitHub\xgboost\R-package/DESCRIPTION' ... OK
* preparing 'xgboost':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
Avis : l'exécution de la commande '"C:/PROGRA~1/R/R-31~1.2/bin/x64/Rcmd.exe" INSTALL -l "C:\Users\mbenesty\AppData\Local\Temp\RtmpyOqJIb\Rinst4fb0344d2d6a" --no-multiarch "C:/Users/mbenesty/AppData/Local/Temp/RtmpyOqJIb/Rbuild4fb0425f7057/xgboost"' renvoie un statut 1
      -----------------------------------
* installing *source* package 'xgboost' ...
** libs
cp -r ../../src .
cp: cannot stat `../../src': No such file or directory
make: *** [xgblib] Error 1
Avis : l'exécution de la commande 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-31~1.2/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-31~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="xgboost.dll" WIN=64 TCLBIN=64 ' renvoie un statut 2
ERROR: compilation failed for package 'xgboost'
* removing 'C:/Users/mbenesty/AppData/Local/Temp/RtmpyOqJIb/Rinst4fb0344d2d6a/xgboost'
      -----------------------------------
ERROR: package installation failed
Error: Command failed (1)
```

**Comment by hetong007** [comment]
I confirm that I met it under and only under Ubuntu as well.

**Comment by hetong007** [comment]
Now I can install it sucessfully on Ubuntu 14.04. Update your `devtools` could be a possible fix : https://github.com/hadley/devtools#updating-to-the-latest-version-of-devtools

**Comment by hetong007** [comment]
To follow up, I encountered a similar problem. It is OK to install from github under Windows 7. However if I want to build vignettes as well, I will get the following information:

```
> devtools::install_github('tqchen/xgboost',subdir='R-package',build_vignettes = TRUE)
Downloading github repo tqchen/xgboost@master
Installing xgboost
"D:/R/R-31~1.2/bin/x64/R" --vanilla CMD build  \
  "C:\Users\hetong\AppData\Local\Temp\RtmpqsRUzS\devtools443877e66a4\tqchen-xgboost-8e93b18\R-package"  \
  --no-resave-data --no-manual 

* checking for file 'C:\Users\hetong\AppData\Local\Temp\RtmpqsRUzS\devtools443877e66a4\tqchen-xgboost-8e93b18\R-package/DESCRIPTION' ... OK
* preparing 'xgboost':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
Warning: running command '"D:/R/R-31~1.2/bin/x64/Rcmd.exe" INSTALL -l "C:\Users\hetong\AppData\Local\Temp\Rtmpugl9xS\Rinst547c4f7218c6" --no-multiarch "C:/Users/hetong/AppData/Local/Temp/Rtmpugl9xS/Rbuild547c3d9059d7/xgboost"' had status 1
      -----------------------------------
* installing *source* package 'xgboost' ...
** libs
cp -r ../../src .
cp: cannot stat `../../src': No such file or directory
make: *** [xgblib] Error 1
Warning: running command 'make -f "Makevars.win" -f "D:/R/R-31~1.2/etc/x64/Makeconf" -f "D:/R/R-31~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="xgboost.dll" WIN=64 TCLBIN=64 ' had status 2
ERROR: compilation failed for package 'xgboost'
* removing 'C:/Users/hetong/AppData/Local/Temp/Rtmpugl9xS/Rinst547c4f7218c6/xgboost'
      -----------------------------------
ERROR: package installation failed
Error: Command failed (1)
```

On Fedora there's error as well:

```
> devtools::install_github('tqchen/xgboost',subdir='R-package',build_vignettes=T)
Downloading github repo tqchen/xgboost@master
Installing xgboost
'/usr/local/lib64/R/bin/R' --vanilla CMD build  \
  '/tmp/Rtmpf8AkcA/devtools725211c224/tqchen-xgboost-8e93b18/R-package'  \
  --no-resave-data --no-manual 

* checking for file ‘/tmp/Rtmpf8AkcA/devtools725211c224/tqchen-xgboost-8e93b18/R-package/DESCRIPTION’ ... OK
* preparing ‘xgboost’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
      -----------------------------------
* installing *source* package ‘xgboost’ ...
** libs
g++ -I/usr/local/lib64/R/include -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I../../ -I/usr/local/include   -fopenmp -fpic  -g -O2  -c xgboost_R.cpp -o xgboost_R.o
xgboost_R.cpp:7:37: fatal error: wrapper/xgboost_wrapper.h: No such file or directory
 #include "wrapper/xgboost_wrapper.h"
                                     ^
compilation terminated.
make: *** [xgboost_R.o] Error 1
ERROR: compilation failed for package ‘xgboost’
* removing ‘/tmp/RtmpoSbeVe/Rinst77075a60655/xgboost’
      -----------------------------------
ERROR: package installation failed
Error: Command failed (1)
```

**Comment by pommedeterresautee** [comment]
@hetong007 From my understanding, `build()` function build the vignette the same way the github installation do. Obviously our error messages are very similar.

I find it strange to be able to build the vignette when I use the dedicated command and not been able to do it with the main `build()` function.

One thing I have understood when analysing `make Rpack` logs is that when you want to build vignette, a first compilation is done without vignette, the package is installed, vignette is generated, then a new version of the package is generated with the generated vignette.

I think the double compilation is the source of the log messages related to the presence of .o objects in the source code.

Kind regards,
Michael

**Comment by hetong007** [comment]
@pommedeterresautee Yes it will build it twice. As the [official guide](http://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Building-package-tarballs) says

> Unless R CMD build is invoked with the --no-build-vignettes option (or the package’s DESCRIPTION contains ‘BuildVignettes: no’ or similar), it will attempt to (re)build the vignettes (see Writing package vignettes) in the package. To do so it installs the current package into a temporary library tree, but any dependent packages need to be installed in an available library tree (see the Note: at the top of this section).

It seems to me that the first installation procedure should not have an effect on the second run.

**Comment by ayikara** [comment]
Is there a command I can use to build without vignettes. Currently using the
devtools::install_github('dmlc/xgboost',subdir='R-package')
What modificaton need to be done

**Comment by brach** [comment]
Is anyone able to do a new installation in R? I've tried on 2 different machines and I'm getting the same error (see below). I'm running R 3.1.3, RTools 3.1, and devtools 1.7.0.9000.


> devtools::install_github('dmlc/xgboost',subdir='R-package')
Downloading github repo dmlc/xgboost@master
Installing xgboost
"C:/apps/R/R-3.1.3/bin/x64/R" --vanilla CMD INSTALL  \
  "C:/Users/gpshymki/AppData/Local/Temp/RtmpCoS1Oq/devtools5b0870de1b01/dmlc-xgboost-c8c1dc6/R-package"  \
  --library="C:/Users/gpshymki/Documents/R/win-library/3.1" --install-tests 

* installing *source* package 'xgboost' ...
** libs

*** arch - i386
cp -r ../../src .
cp -r ../../wrapper .
cp -r ../../subtree .
g++ -m32 -I"C:/apps/R/R-3.1.3/include" -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I./ -I../..    -I"d:/RCompile/CRANpkg/extralibs64/local/include"  -fopenmp   -O2 -Wall  -mtune=core2 -c xgboost_R.cpp -o xgboost_R.o
gcc -m32 -I"C:/apps/R/R-3.1.3/include" -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I./ -I../..    -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O3 -Wall  -std=gnu99 -mtune=core2 -c xgboost_assert.c -o xgboost_assert.o
g++ -m32 -I"C:/apps/R/R-3.1.3/include" -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I./ -I../..    -I"d:/RCompile/CRANpkg/extralibs64/local/include"  -fopenmp   -O2 -Wall  -mtune=core2 -c wrapper/xgboost_wrapper.cpp -o wrapper/xgboost_wrapper.o
In file included from wrapper/xgboost_wrapper.cpp:19:0:
wrapper/../src/learner/learner-inl.hpp: In member function 'void xgboost::learner::BoostLearner::LoadModel(xgboost::utils::IStream&, bool, bool)':
wrapper/../src/learner/learner-inl.hpp:174:22: warning: right shift count >= width of type [enabled by default]
g++ -m32 -I"C:/apps/R/R-3.1.3/include" -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I./ -I../..    -I"d:/RCompile/CRANpkg/extralibs64/local/include"  -fopenmp   -O2 -Wall  -mtune=core2 -c src/io/io.cpp -o src/io/io.o
g++ -m32 -I"C:/apps/R/R-3.1.3/include" -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I./ -I../..    -I"d:/RCompile/CRANpkg/extralibs64/local/include"  -fopenmp   -O2 -Wall  -mtune=core2 -c src/gbm/gbm.cpp -o src/gbm/gbm.o
g++ -m32 -I"C:/apps/R/R-3.1.3/include" -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I./ -I../..    -I"d:/RCompile/CRANpkg/extralibs64/local/include"  -fopenmp   -O2 -Wall  -mtune=core2 -c src/tree/updater.cpp -o src/tree/updater.o
In file included from src/tree/updater.cpp:8:0:
src/tree/./updater_colmaker-inl.hpp: In member function 'void xgboost::tree::ColMaker<TStats>::Builder::UpdateSolution(const xgboost::ColBatch&, const std::vector<xgboost::bst_gpair>&, const xgboost::IFMatrix&, const xgboost::BoosterInfo&) [with TStats = xgboost::tree::GradStats]':
src/tree/./updater_colmaker-inl.hpp:467:9:   instantiated from 'void xgboost::tree::ColMaker<TStats>::Builder::FindSplit(int, const std::vector<int>&, const std::vector<xgboost::bst_gpair>&, xgboost::IFMatrix*, const xgboost::BoosterInfo&, xgboost::tree::RegTree*) [with TStats = xgboost::tree::GradStats]'
src/tree/./updater_colmaker-inl.hpp:92:9:   instantiated from 'void xgboost::tree::ColMaker<TStats>::Builder::Update(const std::vector<xgboost::bst_gpair>&, xgboost::IFMatrix*, const xgboost::BoosterInfo&, xgboost::tree::RegTree*) [with TStats = xgboost::tree::GradStats]'
src/tree/./updater_colmaker-inl.hpp:38:7:   instantiated from 'void xgboost::tree::ColMaker<TStats>::Update(const std::vector<xgboost::bst_gpair>&, xgboost::IFMatrix*, const xgboost::BoosterInfo&, const std::vector<xgboost::tree::RegTree*>&) [with TStats = xgboost::tree::GradStats]'
src/tree/updater.cpp:34:1:   instantiated from here
src/tree/./updater_colmaker-inl.hpp:423:17: warning: variable 'batch_size' set but not used [-Wunused-but-set-variable]
g++ -m32 -I"C:/apps/R/R-3.1.3/include" -DNDEBUG -DXGBOOST_CUSTOMIZE_MSG_ -DXGBOOST_CUSTOMIZE_PRNG_ -DXGBOOST_STRICT_CXX98_ -DRABIT_CUSTOMIZE_MSG_ -DRABIT_STRICT_CXX98_ -I./ -I../..    -I"d:/RCompile/CRANpkg/extralibs64/local/include"  -fopenmp   -O2 -Wall  -mtune=core2 -c subtree/rabit/src/engine_empty.cc -o subtree/rabit/src/engine_empty.o
subtree/rabit/src/engine_empty.cc:37:30: error: 'ISerializable' has not been declared
subtree/rabit/src/engine_empty.cc:38:30: error: 'ISerializable' has not been declared
subtree/rabit/src/engine_empty.cc:41:33: error: 'ISerializable' does not name a type
subtree/rabit/src/engine_empty.cc:41:48: error: ISO C++ forbids declaration of 'global_model' with no type [-fpermissive]
subtree/rabit/src/engine_empty.cc:42:33: error: 'ISerializable' does not name a type
subtree/rabit/src/engine_empty.cc:42:62: error: ISO C++ forbids declaration of 'local_model' with no type [-fpermissive]
subtree/rabit/src/engine_empty.cc:45:37: error: 'ISerializable' does not name a type
subtree/rabit/src/engine_empty.cc:45:52: error: ISO C++ forbids declaration of 'global_model' with no type [-fpermissive]
subtree/rabit/src/engine_empty.cc:77:13: error: cannot declare variable 'rabit::engine::manager' to be of abstract type 'rabit::engine::EmptyEngine'
subtree/rabit/src/engine_empty.cc:18:7: note:   because the following virtual functions are pure within 'rabit::engine::EmptyEngine':
subtree/rabit/src/../include/rabit/engine.h:97:15: note: 	virtual int rabit::engine::IEngine::LoadCheckPoint(rabit::Serializable*, rabit::Serializable*)
subtree/rabit/src/../include/rabit/engine.h:115:16: note: 	virtual void rabit::engine::IEngine::CheckPoint(const Serializable*, const Serializable*)
subtree/rabit/src/../include/rabit/engine.h:137:16: note: 	virtual void rabit::engine::IEngine::LazyCheckPoint(const Serializable*)
make: *** [subtree/rabit/src/engine_empty.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/apps/R/R-3.1.3/etc/i386/Makeconf" -f "C:/apps/R/R-3.1.3/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="xgboost.dll" ' had status 2
ERROR: compilation failed for package 'xgboost'
* removing 'C:/Users/gpshymki/Documents/R/win-library/3.1/xgboost'
Error: Command failed (1)
>

**Comment by tqchen** [comment]
can you try the newest version again? I think it is now fixed

**Comment by brach** [comment]
It seems to be working now. Thank you so much!!!

**Comment by brach** [comment]
Seems to be working now. Thanks!!! 


     On Thursday, April 9, 2015 12:00 PM, Tianqi Chen <notifications@github.com> wrote:
   

 can you try the newest version again? I think it is now fixed—
