### ISSUE TITLE
XGBoost User Group

### ISSUE THREAD

**Issue by tqchen** [dmlc/xgboost#183]
I am creating a [google group](https://groups.google.com/forum/#!forum/xgboost-user) for more general discussion, question and experience sharing about xgboost, the group will also be used for future announcements of updates and new features. 

I will leave this issue open for comments on how user group could be used in complementary to the issue tracker.

**Comment by dtsmith2001** [comment]
There are so many ways to provide support and discussions these days, it's difficult to know what to do. I like stackexchange myself.

I would suggest you decide on one and only one way you want to support users and facilitate discussion rather than try to answer in multiple places. It's just too hard to track everything down otherwise.

**Comment by kirillseva** [comment]
try https://gitter.im
You can add a badge to your README.md, and it is essentially an IRC chat for a github repo
