### ISSUE TITLE
passing monotone constraints to xgbclassifier?

### ISSUE THREAD

**Issue by dynamics77** [dmlc/xgboost#1953]
Is it possible to pass monotone_constraints params to sklearn API of xgboost (i.e., XGBClassifier)? I would to use xgboost with LIME (https://github.com/marcotcr/lime/blob/master/doc/notebooks/Tutorial%20-%20continuous%20and%20categorical%20features.ipynb) that apparently does not accept DMatrix objects but works well with sklearn interface.

**Comment by sebconort** [comment]
+1 

In insurance pricing, forcing monotone_constraints is very useful.
It would be nice if the sklean API (both XGBClassifier and XGBRegressor) could have monotone_constraints as part of its arguments.

Thanks a lot.

**Comment by mlaprise** [comment]
+1

it would be really useful. Anyone knows if there is any workaround for now ?

**Comment by stolorz** [comment]
Since monotonicity constraint works fine with R, some sort of workaround could be performing the training in R. If you rely on python for doing some preprocessing, you could still do it, then export the data to some universal format (e.g. csv), read in R, do the training, then export the model and use it wherever needed.

**Comment by sebconort** [comment]
It's already possible in the Python API, no need to go through R.
But the sklearn wrapper (XGBClassifier and XGBRegressor) does not embed it, which is not complicated I guess because I do it myself in my local projects by overwriting the fit method of the XGBRegressor class.
Though I am not a good developper, and not sure how I could contribute to the library...
And I think it could be useful for a lot of people

**Comment by mlaprise** [comment]
yep, the xgb.train() method actually support it. Indeed, overriding the fit method seems like a good idea

**Comment by khotilov** [comment]
It should be now possible to pass `monotone_constraints` through kwargs #2338

**Comment by mlaprise** [comment]
👍

**Comment by UserQuestions** [comment]
The last time I checked, one could not actually use monotone constraints with the scikit-learn API. Am I doing something wrong?  Thanks!
