### ISSUE TITLE
how to hide the train-rmse output in each iteration of xgboost() ?

### ISSUE THREAD

**Issue by pacificma** [dmlc/xgboost#2123]
I am using the function 'xgboost()' in the package. I wonder is there any option in the function to stop showing the train-rmse in each iteration? Thanks a lot!

**Comment by Laurae2** [comment]
If you want to hide messages, you can use `verbose = 0` and it should make it silent.

You can also use `xgb.train()` because `xgboost()` is an easy/simple wrapper for `xgb.train()` doing all the work for you (creating the `xgb.DMatrix`, watchlist, etc.). The watchlist is what is printed during each iteration for the metrics you monitor.

**Comment by pacificma** [comment]
That works, thanks a lot!
