### ISSUE TITLE
Proposed PHP Wrapper for XGBoost

### ISSUE THREAD

**Issue by bpachev** [dmlc/xgboost#2138]
A couple months ago, I mentioned on the user group that I needed to integrate XGBoost with PHP in a production environment, and wanted to write a wrapper for it. I got positive feedback, and so I went ahead and wrote a bare-bones wrapper that can evaluate XGBoost models (fork [`here`](https://github.com/bpachev/xgboost)). This wrapper will soon be used in production at the company I work for (the REDX, a lead generation service for real estate agents), and supports both PHP 5 and 7.
   I know PHP isn't exactly a popular language for data scientists, but a **lot** of people use it for other applications where *model evaluation* may be needed. With this wrapper, people could build models using their favorite language, and then deploy them in a PHP production environment (which is what I did).
  I'll add more functionality and documentation to the wrapper. I want to know what people think about the idea. What level does it need to be at before a pull request would be accepted?

**Comment by pommedeterresautee** [comment]
I am not a user of PHP but I totally see a use case in reranking for instance (and XGBoost can do this stuff). May be you want to focus on specific use instead of offering a general framework (just an idea)

**Comment by tqchen** [comment]
I think to be helpful to the community, here are the things that we welcomed

- The API doc and testcases.
- Code examples for people to get started with.

We can also go with two ways. Either create a xgboost-php repo (see [XGBoost.jl](https://github.com/dmlc/xgboost.jl) ), which depends on XGBoost C Library, or merge it back to the main branch. I would recommend to start with former one, since the wrapping is likely won't going to touch anything in the centralized repo.

In either way, we will put up the links to the php project and advertise it in the XGBoost main repo

**Comment by bpachev** [comment]
@tqchen, @pommedeterresautee Thanks for your feedback. I've created a separate repo at https://github.com/bpachev/xgboost-php. I still need to add tests, documentation, and more examples. I will add those shortly.

**Comment by bpachev** [comment]
@tqchen I've added automated tests, documentation and a demo using the Titanic dataset.
I feel like it's ready to be used by the community. What are your thoughts?

**Comment by tqchen** [comment]
great, feel free to create a PR to add it to the awesome XGBoost list. If you have a blogpost introducing it

**Comment by tqchen** [comment]
if you write a blogpost about it. You are also more than welcomed to post a link

**Comment by bpachev** [comment]
Have created a PR with a link to the xgboost-php repo. Currently don't have a blogpost, but may have one in the next couple days.
