### ISSUE TITLE
Propose adding sequence support to "base_score"

### ISSUE THREAD

**Issue by tomwang-wc** [dmlc/xgboost#2222]
There is an simialr oldopen issue #1672 , but nobody comments for a half year. I think the idea in that issue is worth discussing so I open this thread and hope to raise attention.

 In #1672 fakyras said setting different reasonable base_scores for each row could make trianing faster and training also could gain benefits from pre-trained models' biases as a new start.
> I did not find if anyone came up with setting different base_scores for each training row for first xgboost iteration? In a case i am working on it could speed up xgboost training time drastically; It would also be a nice option as a "continued" training, using initial biases from other pre-trained model. Would this be hard to implement?

I agree with faryras. I think using pre-trained model as initial values is a great idea. And applying various not same base_score for all samples may optain better local optimum and make more room for optimization. As for implementation issue, I looked into python package and found no way to realize this and sadly I don't understand c++. 

Guys, what‘re your opinoins? Is it worth implementing?

**Comment by khotilov** [comment]
This functionality was available for long time. See the examples in [boost_from_prediction.R](https://github.com/dmlc/xgboost/blob/d281c6aafa694d79fb39bf040c3dece40505092c/R-package/demo/boost_from_prediction.R) or [boost_from_prediction.py](https://github.com/dmlc/xgboost/blob/d281c6aafa694d79fb39bf040c3dece40505092c/demo/guide-python/boost_from_prediction.py). I will add some information to the xgboost parameters documentation page to make this functionality easier to find.

Note that instead of already transformed `base_score`, `base_margin` needs raw margin values (i.e., before applying inverse-link transformation). E.g., for binary logistic objective, `base_score` would be on the probability scale, while `base_margin` would need to be on the logit-of-probability scale. Also note that in multiclass setting, each row would have to have `num_class` values of `base_margin`, which makes it possible to have different starting values per class.

**Comment by tomwang-wc** [comment]
Thank you khotilov, thanks for your time and notes. I should have looked the demo carefully.
