### ISSUE TITLE
[jvm-packages] Providing group data for rank tasks in xgboost4j-spark params is error prone

### ISSUE THREAD

**Issue by ebernhardson** [dmlc/xgboost#2223]
Providing a Seq[Seq[Int]] of group data in the XGBoost::trainWithDataFrame function makes it very easy for a user to shoot themselves in the foot. If the number of workers selected isn't the same as the number of partitions, then it will repartition the dataframe. Once the dataframe is repartitioned the provided group data is no longer valid. A more resilient solution might be to accept a group column. 

If not possible, at least some documentation on how to generate this group data would also be useful. Currently my process is roughly:

* Convert my dataframe into a PairRDD[(String, Row)] with the group identifier as the key
* repartition by key, sort within partitions so groups are sequential
* convert PairRDD back into RDD[Row] then into DataFrame
* map over partitions with the partition index, creating a new RDD[(Int, Int)] of (partition id, group length) pairs. 
* Collect that rdd and build up the Seq[Seq[Int]]

This feels quite wrong, but I can't put my finger on what the right way would be given the provided interface.

**Comment by CodingCat** [comment]
would you mind titled with `[jvm-packages]` when you refer to a jvm problem

**Comment by CodingCat** [comment]
a simple solution is to stop the process when the repartition is required

wrap this: https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala#L275 and the check for group data issue in a new helper function `validateParams(...)`

**Comment by lblaese** [comment]
I opened a similar thread because I didn't see this one, so let's continue that here.
I agree that using the Seq[Seq[Int]] approach is flawed. Not only when the number of groups differs from the number of executors, but also when shuffling operations occur (e.g. sorting, repartition, etc)...

The correct way to solve that (IMHO) is to extend LabeledPoint to incorporate the group info, so we have something like 
`GroupedLabeledPoint(group: Option[Int] = None, label: Double, features: Vector) extends LabeledPoint(label, features)`

and add some implicits to make conversions (if necessary) seamless
