### ISSUE TITLE
[jvm-packages] Any suggestions of xgboost4j-spark parameters(nworker, nthread, num-executor, executor-core)?

### ISSUE THREAD

**Issue by cnglen** [dmlc/xgboost#2266]
Any suggestion of setting spark parameters? What's the relationship with the following 4 parameters?

- nworker
- nthread
- num-exectutors
- executors-cores

I find: the larger executor-cores,  the slower the training time.

**Comment by CodingCat** [comment]
would you please add [jvm-packages] in your issue title when you ask about jvm packages questions, so that I can quickly identify that?

**Comment by CodingCat** [comment]
> nworker

it's just how many parallel workers you would like to run for xgboost

> nthread

it's how many threads used by each worker, by default you do not need to set it, unless you enable openmp when compile xgboost

> num-exectutors & executors-cores

these are more spark specific params, when you have larger executors-cores, it's possible that the resource contention is intensive within an executor. For example, when you run spark in YARN and you over-subscribe physical cores, then you might have some problems since xgboost is kind of cpu intensive...
