### ISSUE TITLE
Removing default "rmse" for "reg:linear"

### ISSUE THREAD

**Issue by saj1919** [dmlc/xgboost#2309]
I want to keep objective as "reg:linear" and eval_metric as customised rmse as follows.

```
def customised_rmse(preds, dtrain):
    N = len(preds)
    preds = np.array(preds)
    actual = np.array(dtrain.get_label())
    crmse = np.sqrt(np.sum(np.power((preds+1)*1.0/(actual+1) - 1.1, 2))/N)
    return "custom-rmse", crmse
```

When I ran, train function as follows ->
`model = xgb.train(param_list, xgb_train, num_rounds, watchlist, None, customised_rmse, early_stopping_rounds=30)`

Output I am getting is this ->
```
[0] train-rmse:15.1904  val-rmse:15.2102    train-custom-rmse:0.607681  val-custom-rmse:0.610993
Multiple eval metrics have been passed: 'val-custom-rmse' will be used for early stopping.
Will train until val-custom-rmse hasn't improved in 30 rounds.
[1] train-rmse:14.4936  val-rmse:14.5103    train-custom-rmse:0.588831  val-custom-rmse:0.589902
.
.
. and so on
```

My question is, it is getting optimised using "rmse" or "custom-rase" or both ?? 
What I have to do to remove "rmse" as it comes by default with "reg:linear" ??

**Comment by ungil** [comment]
`Multiple eval metrics have been passed: 'val-custom-rmse' will be used for early stopping.`

Doesn't this respond to your first question?

**Comment by saj1919** [comment]
@ungil Hey that is clear. But my point is when we don't set any objective, "reg:linear" is selected by default and if we set different objective function then what will happen ?? Will it take new-objective function with rmse and custom-rase or will it take "reg:linear" ??

**Comment by ungil** [comment]
I misunderstood your question, but I still don't understand wha you are trying to do. You're using the default objective (reg:linear = minimise rmse). The metric rmse will be calculated and displayed at each iteration. You have defined a custom metric that will also be calculated and displayed and it's being used for the early stopping in the cross validation.

I think if you set a different objective function you will see different metric by default (instead of rmse in your example) and you will still see the custom metric that you defined which will be used for the early stopping in the cross validation.

**Comment by saj1919** [comment]
Yup. Got it. Writing only eval-function doesn't make sense. Need to write special objective for the same. Then it shows the changed values. Thanks.
