### ISSUE TITLE
xgboost is not available for R version 3.4.0 (drat repository)

### ISSUE THREAD

**Issue by BlindApe** [dmlc/xgboost#2374]
install.packages("xgboost", repos="http://dmlc.ml/drat/", type = "source")
Warning message:
package ‘xgboost’ is not available (for R version 3.4.0) 

@thirdwing , last time you updated the rat repository, could you please do it again?
Thank you!

**Comment by thirdwing** [comment]
Please try again now

```
> install.packages("xgboost", repos="http://dmlc.ml/drat/", type = "source")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'http://dmlc.ml/drat/src/contrib/xgboost_0.6.4.5.tar.gz'
Content type 'application/octet-stream' length 460176 bytes (449 KB)
==================================================
downloaded 449 KB

* installing *source* package ‘xgboost’ ...
configure: creating ./config.status
config.status: creating src/Makevars
......
```

**Comment by ck37** [comment]
Works well for me, thanks. https://ci.appveyor.com/project/ck37/superlearner/build/1.0.162/job/xsscstu7wa392s54#L142

**Comment by BlindApe** [comment]
Works for me too (with same warnings)
Thank you!

**Comment by BudiRustandi** [comment]
I use RStudio under OSX Mac El Capitan.

I got the following messages:
Warning in install.packages :
  installation of package 'xgboost' had non-zero exit status

Probably it's because I don't have OpenMP, as there are some messages related to OpenMP not available. How do I activate the OpenMP? I'm trying to install OpenMP, but it seems it doesn't work with the latest XCode.

Appreciate your help in guiding me in installing the OpenMP. Or can I turn off the OpenMP during XGBoost installation?

**Comment by khotilov** [comment]
@BudiRustandi did you read https://xgboost.readthedocs.io/en/latest/build.html ?

**Comment by BudiRustandi** [comment]
@khotilov , I tried following the instructions from the link, but I got error when compiling: thread-local storage is not supported for the current target.

I think I just stick with the XGBoost from CRAN repository. Is there any disadvantage of using XGBoost from CRAN, as oppose to get from the GITHUB?

Thanks for your help
