### ISSUE TITLE
Purpose of -msse2 flag used while compiling the xgboost source code 

### ISSUE THREAD

**Issue by snehlatamohite** [dmlc/xgboost#2446]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System:
Ubuntu

Compiler:
CPP

Package used (python/R/jvm/C++):
python,C++

`xgboost` version used:
cloned from master branch & build from source

The python version and distribution
python3.5

## Steps to reproduce
1.make -j4

Its been observed that -msse2 flag is used while compiling the code. We have not found any SSE/Intel specific code available in xgboost source code. Can we remove the flag since it is no longer needed? 
It will help to compile code different architectures (apart from x86) without changes.

Please advise.

**Comment by superbobry** [comment]
I think without `-msse2` the compiler would assume a generic architecture and would not vectorize loops nor emit any SSE2 instructions. That being said, the compilation should probably do feature discovery and enable `-msse2` only if the host supports it.

**Comment by lakshayg** [comment]
Shouldn't using `-march=native` be a better idea to enable all the architecture specific optimizations automatially?

**Comment by superbobry** [comment]
It's not if you want the code to run on different hardware that the host you compile on, e.g. running distributed XGBoost on the cluster.

**Comment by snehlatamohite** [comment]
I have checked in xgboost code and there are no SSE2 instructions available in the code , so I did not understood the purpose of msse2 flag. 
If we replace it -march=native or remove msse2  flag , then we can compile xgboost code on all architectures. 
Please suggest.

**Comment by thirdwing** [comment]
I think this can be solved like what has been done in MXNet: https://github.com/dmlc/mxnet/blob/master/make/config.mk#L119-L124

**Comment by RAMitchell** [comment]
This stack overflow post https://stackoverflow.com/a/10687419 suggests that this flag is redundant as it is always enabled.

Should we just remove the flag?

**Comment by khotilov** [comment]
When the loop vectorization was initially implemented in gcc, explicit use of `-msse` or `-msse2` was one of the required things in order to enable it (according to the old document at https://gcc.gnu.org/projects/tree-ssa/vectorization.html ). However, it looks like this is not necessary anymore since some gcc version, and the corresponding sse flags are automatically added. E.g., with gcc 4.9.3:
```
$ cat ex.c
int a[256], b[256], c[256];
void f() {
  int i;
  for (i=0; i<256; i++){
    a[i] = b[i] + c[i];
  }
}

$ g++ -m64 -O3 -fopt-info-vec-optimized -S -fverbose-asm ex.c
ex.c:4:3: note: loop vectorized

$ grep sse ex.s
 # options passed:
 # -mno-sse4 -mpush-args -mred-zone -msse -msse2 -msse3 -mstack-arg-probe

$ grep vector ex.s
 # -ftree-loop-ivcanon -ftree-loop-optimize -ftree-loop-vectorize
 # -ftree-slp-vectorize -ftree-slsr -ftree-sra -ftree-switch-conversion
```
Experimenting with https://godbolt.org/ , even with gcc 4.4.7 I see `-ftree-vectorize` and `-msse2` enabled when using `-O3`.

On the other hand, I'm skeptical about the current use of the `-funroll-loops` flag. Complete loop unrolling, when possible, is already a part of the -O3 optimizations anyway. The extra unrollings by `-funroll-loops` increase code size (I saw ~ 15% increase), and may or may not help performance (in a single run I didn't notice any significant effect though). They also might interfere with the loop vectorizations (compiling with the `-fopt-info-loop-optimized` showed that the two optimizations are frequently done together within same loop).
