### ISSUE TITLE
Predicting in submilliseconds

### ISSUE THREAD

**Issue by MohNil** [dmlc/xgboost#2551]

**Comment by hcho3** [comment]
Lately there's been greater interest in faster prediction. In the near future, the dmlc group will host a new project (provisionally named) **tree-lite** that is dedicated to improving prediction speed.

Some facts about tree-lite:
* It will read your (already trained) tree ensemble model and produce an **optimized prediction library**.
* We aim to provide a **well assorted toolbox** of methods that are known to improve prediction speed. People will be able to experiment with it on their own. Good engineering will be essential in this effort --- see how xgboost lets people experiment more rapidly with tree models.
* It will support multiple tree formats, so that you can use other packages (e.g. LightGBM) to train your model.

The project is currently private, but we are working hard to make it public in the near future. Stay tuned!
