### ISSUE TITLE
max_bin documentation incorrect

### ISSUE THREAD

**Issue by RAMitchell** [dmlc/xgboost#2567]
@hcho3 
I notice that our parameter documentation refers to the value 'max_bins' but the parameter itself within XGBoost is 'max_bin'.

I believe this has led to incorrect results in this blog article:
https://blogs.technet.microsoft.com/machinelearning/2017/07/25/lessons-learned-benchmarking-fast-machine-learning-algorithms/

I also notice that in all of our tree algorithms we initialise parameters allowing unknowns. If at all possible I think we should change this to prevent these kind of ambiguities in future.

**Comment by hcho3** [comment]
@RAMitchell I've submitted a PR to fix the misspelling.

It would take a non-trivial amount of modification to disallow unknown parameters, as many different parameter structures (`CLIParam`, `FastHistParam`, `GBTreeTrainParam` and so forth) draw from the common pool of arguments. For instance, an argument that is "unknown" to `CLIParam` may be later accepted by `GBTreeTrainParam`. We'd need to keep track of which arguments have been picked up by parameter structures and which have not.

@tqchen Any idea about the unknown parameter issue? The cleanest way I can think of is to add a new interface `InitConsume(&cfg)` to DMLC parameter module. The new interface would physically remove arguments from the pool, so that we can tell which arguments in the list have been used or not. Just before training starts, we can check if `cfg` is empty or not.

**Comment by hcho3** [comment]
@tqchen Actually, never mind. We could simply keep a (hidden) static database of used parameters. Let's try not to modify the DMLC module if possible.

**Comment by RAMitchell** [comment]
It would also be nice to express more sophisticated relationships between parameters. E.g. if I design a tree_updater algorithm I could declare that it supports the subsample parameter but not monotonic constraints.

**Comment by hcho3** [comment]
@RAMitchell I agree that it would be nice, although I suspect it would involve updating the DMLC parameter module. For now, I'd put it on a long-term wish list.

@tqchen I've submitted a provisional PR to implement detection of unused parameters. See #2571.
