### ISSUE TITLE
Does random data sampling occur when subsample is set to 1 (the default)?

### ISSUE THREAD

**Issue by kuo000** [dmlc/xgboost#266]
When the parameter "subsample" is set to 1 (as default), does xgboost still do random sampling (with replacement) but the sample size is just the same as that of the entire dataset? Or there's simply no random sampling, i.e., the original dataset is used in every iteration?

Thanks.

**Comment by pommedeterresautee** [comment]
No random sampling when set to 1.

If you want to use this parameter don't forget to increase the number of rounds accordingly.
Otherwise not all data would be seen by the algorithms. Or not enough times.
If I answered your question please close this issue.

If you have other questions we have a dedicated forum where to discuss.

Kind regards,
Michaël
