### ISSUE TITLE
[jvm-packages] Scala first, Java second

### ISSUE THREAD

**Issue by superbobry** [dmlc/xgboost#2713]
Disclaimer: this is a somewhat philosophical question. 

The current codebase has a lot of duplication between Java & Scala, in part due to the crappy Java interop Scala offers. For instance, there is `java.DMatrix` and `scala.XGBoost`, `java.XGBoost` and `scala.XGBoost`, `java.IEvaluation` and `scala.EvalTrait` etc. Supporting two duplicated codebases is no fun, so I suggest to consider leaving one of the languages as first-class and supporting the second one as best-effort. To me, the choice between Scala and Java is obvious: Scala. In part due to well-known Java verbosity and in part due to Spark, which also treats Scala as first-class, especially when it comes to data frames.

Sidenote: a more extreme solution would be to stay in Java-land and use Kotlin to write a fully Java-compatible API. This would make data frame interactions a bit less elegant, but I think it could still worth a try.

What do you think?

**Comment by Yunni** [comment]
I vote for Scala as well because it's really verbose to call some of the Spark API in Java. But AFAIK there are a number of incompatibility issues when calling Scala in Java (i.e. default parameter values). I suggest to implement a number of integration tests like these (and run them on CI): https://github.com/apache/spark/tree/master/examples/src/main/java/org/apache/spark/examples/ml

**Comment by CodingCat** [comment]
I didn't understand it very well.....if I vote for Scala what will you do? if I vote for Java what will you do?

**Comment by superbobry** [comment]
I would replace all (or as many as I can) Java classes with Scala ones ensuring that they are bearable to call from Java.

> But AFAIK there are a number of incompatibility issues when calling Scala in Java [...]

Yeah, unfortunately making Scala API look sane in Java is tricky, but we can try.

**Comment by CodingCat** [comment]
what's the current problem with Java-implemented classes....

Just because at the very beginning, there was only Java bindings of XGBoost, so when I started scala-relevant stuffs, I did not want to change it too much

The only issue I can remember is that Java-based solution has to expose some classes as public to be used by scala...maybe I forgot some of them

**Comment by superbobry** [comment]
The problem is duplication and the need for wrapping Java APIs in Scala, as I've highlighted above. I don't claim it's a pressing issue, I just wanted to get the discussion going.

A more extreme alternative would be to a) get rid of .java/.scala in package name and try to minimize the duplication, e.g. collapse eval/objective traits.

**Comment by CodingCat** [comment]
well, I definitely prefer Scala if I have to choose

so, we will leave only one package in the repo?

**Comment by Craigacp** [comment]
I'd prefer not to carry around the Scala jars if I don't have to, and at the moment I can use XGBoost purely from Java. Scala has usability issues as it has no forwards compatibility (i.e. you have to compile XGBoost with the same Scala version you use elsewhere), and also Scala 2.11 isn't compatible with Java 9, so a pure Scala solution won't run on the latest JVM.

**Comment by superbobry** [comment]
Thanks for the input @Craigacp. Are you using plain xgboost4j or the Spark version?

**Comment by Craigacp** [comment]
Plain xgboost4j. People tend to complain at me when their deployed war file gets 25mb bigger because I’m carrying around Scala, and I need to be able to deploy it on Java 9 as well, so Scala causes problems for me.
