### ISSUE TITLE
Python Installation

### ISSUE THREAD

**Issue by ManSoSec** [dmlc/xgboost#272]
Hi,

An strange thing happened for me. Before installation, when I was running XGBoost on a dataset, the logloss I had achieved is a bit better (lower) than after I installed XGBoost by setup.py.
Do you know what is the reason ?

Thanks a lot.

**Comment by tqchen** [comment]
This could due to the version change. Depending on what version you are using. There was a change of [Logs loss evaluation](https://github.com/dmlc/xgboost/blob/master/src/learner/evaluation-inl.hpp#L86) to cap extreme values. I do not know if that was the reason. 

If you do not think so, try provide a hashtag of your old version a code to reproduce that

**Comment by ManSoSec** [comment]
I don't use the logloss of XGBoost. I uploaded my result on the kaggle and it produced the logloss.
I had downloaded it on 4th of April. The version mentioned in the readme is xgboost-0.3.

The difference is not a lot. Previous version : 0.0098 , New version : 0.0100
But I was wondering Why ?

Thanks again.

**Comment by tqchen** [comment]
This could due to some indeterminism in multi-threading in floating summation. Similar issues was discussed in #13

**Comment by ManSoSec** [comment]
Ok, Thanks a lot.
