### ISSUE TITLE
CMake Error at gpuxgboost_generated_updater_gpu_hist_experimental.cu.obj.Release.cmake:282

### ISSUE THREAD

**Issue by putsandcalls** [dmlc/xgboost#2762]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: Windows 10

Compiler: Visual Studio 14 2015 Win 64

Package used (python/R/jvm/C++):

`xgboost` version used: Latest

I am having trouble building the libxgboost.dll file for xgboost with GPU support. I have followed all the instructions and have used cmake 3.8.2 to obtain the build folder. However, I am having difficulties compiling the .sln file. In particular, I am getting an error saying
```



Error		'cicc' died with status 0xC0000005 (ACCESS_VIOLATION)	gpuxgboost	C:\Users\johnz\xgboost\build\CUSTOMBUILD	1	

Error	LNK1104	cannot open file 'Release\gpuxgboost.lib'	runxgboost	C:\Users\johnz\xgboost\build\LINK	1	

  updater_gpu_hist.cu
  Building NVCC (Device) object CMakeFiles/gpuxgboost.dir/src/tree/Release/gpuxgboost_generated_updater_gpu_hist_experimental.cu.obj
  updater_gpu_hist_experimental.cu
c:\users\johnz\xgboost\dmlc-core\include\dmlc\./optional.h(26): warning : "constexpr" is ignored here in Microsoft mode
  
c:\users\johnz\xgboost\dmlc-core\include\dmlc\./optional.h(26): warning : "constexpr" is ignored here in Microsoft mode
  
c:\users\johnz\xgboost\dmlc-core\include\dmlc\./optional.h(26): warning : "constexpr" is ignored here in Microsoft mode
  
c:\users\johnz\xgboost\dmlc-core\include\dmlc\./optional.h(26): warning : "constexpr" is ignored here in Microsoft mode
  
c:\users\johnz\xgboost\dmlc-core\include\dmlc\./optional.h(26): warning : "constexpr" is ignored here in Microsoft mode
  
c:\users\johnz\xgboost\dmlc-core\include\dmlc\./optional.h(26): warning : "constexpr" is ignored here in Microsoft mode
  
  updater_gpu_hist_experimental.cu
CUSTOMBUILD : nvcc error : 'cicc' died with status 0xC0000005 (ACCESS_VIOLATION)
  CMake Error at gpuxgboost_generated_updater_gpu_hist_experimental.cu.obj.Release.cmake:282 (message):
    Error generating file
    C:/Users/johnz/xgboost/build/CMakeFiles/gpuxgboost.dir/src/tree/Release/gpuxgboost_generated_updater_gpu_hist_experimental.cu.obj

```

Please help !

**Comment by LaithYZumot** [comment]
Im having the same issue
when running cmake i get
cmake .. -G"Visual Studio 14 2015 Win64" -DR_LIB=ON -DUSE_CUDA=ON
-- The C compiler identification is MSVC 19.0.24225.1
-- The CXX compiler identification is MSVC 19.0.24225.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found PythonInterp: C:/Users/Laith/Anaconda3/python.exe (found version "3.5.4")
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0 (found suitable version "9.0", minimum required is "7.5")
Error: unexpected end of input
Execution halted
 * [C:/Program Files/R/R-3.4.1/bin/x64/R.dll] Found PE+ image
-- Found LibR: C:/Program Files/R/R-3.4.1
-- Found R: C:/Program Files/R/R-3.4.1/bin/x64/R.exe
-- LIBR_CORE_LIBRARY C:/xgboost/build/R.lib
-- Configuring done
-- Generating done
-- Build files have been written to: C:/xgboost/build

and then compiling fails... running without CUDA option goes ok

**Comment by LaithYZumot** [comment]
i am having a similar problem 
  CUSTOMBUILD : nvcc error : 'cicc' died with status 0xC0000005 (ACCESS_VIOLATION) [C:\xgboost\build\gpuxgboost.vcxproj

Operating System: Windows 10
Compiler: Visual Studio 14 2015 Win 64
cmake command: cmake .. -G"Visual Studio 14 2015 Win64" -DUSE_CUDA=ON -DGPU_COMPUTE_VER=61 -DR_LIB=ON

**Comment by ljkong** [comment]
Got exactly the same problem.


==== console ====
Building NVCC (Device) object CMakeFiles/gpuxgboost.dir/src/tree/Release/gpuxgboost_generated_updater_gpu_hist_experi
  mental.cu.obj
  updater_gpu_hist_experimental.cu
c:\workspace\xgboost\xgboost\dmlc-core\include\dmlc\./optional.h(26): warning : "constexpr" is ignored here in Microsof
t mode [C:\workspace\xgboost\xgboost\build\gpuxgboost.vcxproj]

c:\workspace\xgboost\xgboost\dmlc-core\include\dmlc\./optional.h(26): warning : "constexpr" is ignored here in Microsof
t mode [C:\workspace\xgboost\xgboost\build\gpuxgboost.vcxproj]

c:\workspace\xgboost\xgboost\dmlc-core\include\dmlc\./optional.h(26): warning : "constexpr" is ignored here in Microsof
t mode [C:\workspace\xgboost\xgboost\build\gpuxgboost.vcxproj]

c:\workspace\xgboost\xgboost\dmlc-core\include\dmlc\./optional.h(26): warning : "constexpr" is ignored here in Microsof
t mode [C:\workspace\xgboost\xgboost\build\gpuxgboost.vcxproj]

c:\workspace\xgboost\xgboost\dmlc-core\include\dmlc\./optional.h(26): warning : "constexpr" is ignored here in Microsof
t mode [C:\workspace\xgboost\xgboost\build\gpuxgboost.vcxproj]

c:\workspace\xgboost\xgboost\dmlc-core\include\dmlc\./optional.h(26): warning : "constexpr" is ignored here in Microsof
t mode [C:\workspace\xgboost\xgboost\build\gpuxgboost.vcxproj]

  updater_gpu_hist_experimental.cu
CUSTOMBUILD : nvcc error : 'cicc' died with status 0xC0000005 (ACCESS_VIOLATION) [C:\workspace\xgboost\xgboost\build\gp
uxgboost.vcxproj]
  CMake Error at gpuxgboost_generated_updater_gpu_hist_experimental.cu.obj.Release.cmake:282 (message):
    Error generating file
    C:/workspace/xgboost/xgboost/build/CMakeFiles/gpuxgboost.dir/src/tree/Release/gpuxgboost_generated_updater_gpu_hist
  _experimental.cu.obj
================

OS: Windows 10 Pro V1703 Build 15063.674
CPU: Intel Core i7-6600U
GPU: NVidia GeForce GTX 965M
CUDA: Version 8.0.61
R: 3.4.2
RBuildTools: 3.4


Thanks.

**Comment by IdoWSC** [comment]
I have the same problem.

**Comment by RAMitchell** [comment]
This issue appears to be related to cuda 8.0.61. Rolling back to version 8.0.44 or upgrading to cuda 9 may solve the problem.
dmlc#5308

**Comment by ljkong** [comment]
@RAMitchell Thanks for the information and the link. I rolled CUDA back to 8.0.44 (Tensorflow 1.4 doesn't support CUDA 9) and the error disappeared. So this issue should be related to CUDA 8.0.61 release.
However I just got another error when linking all the obj files. somehow the linker just can't find the necessary files so that there're so many unresolved external symbols. I double checked R.lib is there in the build dir and R.dll has been found already (I made a copy into the build dir as well). not sure what went wrong...
==============================================
init.obj : error LNK2019: unresolved external symbol R_registerRoutines referenced in function R_init_xgboost [C:\workspace\xgboost\xgboost\build\xgboost.v
cxproj]
init.obj : error LNK2019: unresolved external symbol R_useDynamicSymbols referenced in function R_init_xgboost [C:\workspace\xgboost\xgboost\build\xgboost.
vcxproj]
xgboost_assert.obj : error LNK2019: unresolved external symbol Rf_error referenced in function XGBoostAssert_R [C:\workspace\xgboost\xgboost\build\xgboost.
vcxproj]
xgboost_R.obj : error LNK2001: unresolved external symbol Rf_error [C:\workspace\xgboost\xgboost\build\xgboost.vcxproj]
xgboost_custom.obj : error LNK2001: unresolved external symbol Rf_error [C:\workspace\xgboost\xgboost\build\xgboost.vcxproj]
xgboost_R.obj : error LNK2019: unresolved external symbol R_CHAR referenced in function XGBoosterDumpModel_R [C:\workspace\xgboost\xgboost\build\xgboost.vc
xproj]
xgboost_R.obj : error LNK2019: unresolved external symbol Rf_isNull referenced in function XGBoosterSetAttr_R [C:\workspace\xgboost\xgboost\build\xgboost.v
cxproj]
xgboost_R.obj : error LNK2019: unresolved external symbol TYPEOF referenced in function XGDMatrixCreateFromMat_R [C:\workspace\xgboost\xgboost\build\xgboos
t.vcxproj]
xgboost_R.obj : error LNK2019: unresolved external symbol INTEGER referenced in function XGDMatrixCreateFromCSC_R [C:\workspace\xgboost\xgboost\build\xgboo
st.vcxproj]
xgboost_R.obj : error LNK2019: unresolved external symbol RAW referenced in function XGBoosterLoadModelFromRaw_R [C:\workspace\xgboost\xgboost\build\xgboos
t.vcxproj]
...

**Comment by jeremiedb** [comment]
@ljkong Have you resolved your issue? I just got the same linking errors, same issue arise if compiling only for CPU with VS2015.

**Comment by jeremiedb** [comment]
Issue  happened to be with Rtools: need to have `C:\Rtools\bin` and `C:\Rtools\mingw_64\bin` in path, and not  \`C:\Rtools\mingw_32\bin`.

**Comment by ljkong** [comment]
@jeremiedb thanks for the update there. I have switched to linux/ubuntu where has no any drama but I will try it in future in Windows. Thanks.
