### ISSUE TITLE
[jvm-packages] Get number of rounds from XGBoost Spark Cross Validation

### ISSUE THREAD

**Issue by xiaozhouwang** [dmlc/xgboost#2843]
First of all, I want to say that XGBoost Spark is greatly developed and thank you so much for all xgboost contributors' hard work!!

Now back to the question I want to ask.:)
So I am following the example here 
https://docs.databricks.com/_static/notebooks/xgboost.html

Specifically the "Tune Model using MLlib Cross Validation" part to do cross validation. So in the end, 
we get something like this:
```
cvModel.bestModel.extractParamMap
res4: org.apache.spark.ml.param.ParamMap =
{
	XGBoostRegressionModel_f3425b374335-alpha: 0.0,
	XGBoostRegressionModel_f3425b374335-booster: gbtree,
	XGBoostRegressionModel_f3425b374335-colsample_bylevel: 1.0,
	XGBoostRegressionModel_f3425b374335-colsample_bytree: 1.0,
	XGBoostRegressionModel_f3425b374335-eta: 0.6,
	XGBoostRegressionModel_f3425b374335-featuresCol: features,
	XGBoostRegressionModel_f3425b374335-gamma: 0.0,
	XGBoostRegressionModel_f3425b374335-grow_policy: depthwise,
	XGBoostRegressionModel_f3425b374335-labelCol: label,
	XGBoostRegressionModel_f3425b374335-lambda: 1.0,
	XGBoostRegressionModel_f3425b374335-lambda_bias: 0.0,
	XGBoostRegressionModel_f3425b374335-max_bin: 16,
	XGBoostRegressionModel_f3425b374335-max_delta_step: 0.0,
	XGBoostRegressionModel_f3425b374335-max_depth: 7,
	XGBoostRegressionModel_f3425b374335-min_child_weight: 1.0,
	XGBoostRegressionModel_f3425b374335-normalize_type: tree,
	XGBoostRegressionModel_f3425b374335-predictionCol: prediction,
	XGBoostRegressionModel_f3425b374335-rate_drop: 0.0,
	XGBoostRegressionModel_f3425b374335-sample_type: uniform,
	XGBoostRegressionModel_f3425b374335-scale_pos_weight: 1.0,
	XGBoostRegressionModel_f3425b374335-sketch_eps: 0.03,
	XGBoostRegressionModel_f3425b374335-skip_drop: 0.0,
	XGBoostRegressionModel_f3425b374335-subsample: 1.0,
	XGBoostRegressionModel_f3425b374335-tree_method: auto,
	XGBoostRegressionModel_f3425b374335-use_external_memory: false
}
```
But it doesn't seem to have rounds in it? To be more specific, if I set the number of rounds very high, and then set early stopping to find the best iteration, how do I get the best iteration here? I understand that each fold will output different number of trees, but is there a way for user to get access to the information? 

Thank you very much in advance!

**Comment by sethah** [comment]
The problem is that `XGBoostClassificationModel` inherits from `XGBoostModel`, which has the `BoosterParams` trait mixed in, but does not mix in the `GeneralParams` trait where `round` param is defined. So, the `XGBoostClassificationModel` doesn't "own" the `round` param and that doesn't end up getting copied after model fitting.

The solution, IMO, would be to separate out `GeneralParams` into something like `GeneralParams` and `AlgorithmParams` (better ideas for the names?). Then, the model can mix in `AlgorithmParams`, which might contain `round`, `missing`, `customEval`, `customObj` params (ones that you'd want to see in the model), but you can still leave out unimportant ones like `numThreadPerTask` etc...

There may be some reason that I'm not aware of that those parameters aren't copied. Maybe @CodingCat or @superbobry  knows. Thoughts?
