### ISSUE TITLE
What is the difference between xgb.train and xgb.XGRRegressor (or xgb.XGBClassifier) ?

### ISSUE THREAD

**Issue by Statham-stone** [dmlc/xgboost#2861]
I already know "xgboost.XGBRegressor is a Scikit-Learn Wrapper interface for XGBoost."

But do they have any other difference?

BTW, if I use xgb.train, how can i specify the number of the trees in my model ? In xgboost.XGBRegressor, I know i can use parameter ’n_estimators‘， but what should i do in xgb.train? 

I searched Google and didn't find any answer, thanks in advance.

**Comment by nareshshah139** [comment]
Hello Statham,

You can set the parameters like n_estimators in a dictionary like 

params = { 'n_estimators' = 100; colsample_by_tree = 10;}

And use that dictionary in xgboost.train(params = params, ...)

Its simply a different API and can make a difference sometimes if you want to use sparse matrix data format instead of a dense matrix data format for example.

**Comment by pommedeterresautee** [comment]
Answer provided. Closing.
