### ISSUE TITLE
Trouble with predict after trained.

### ISSUE THREAD

**Issue by seanamax** [dmlc/xgboost#2874]
## Environment info
Operating System:
Deepin 15.04(Like Ubuntu)

Compiler:
GCC 4.8 version

Package used (python/R/jvm/C++):
Python

`xgboost` version used:
Latest version, 2017/11/13 downdload from github.

1. The commit hash (`git rev-parse HEAD`)
2. Logs will be helpful (If logs are large, please upload as attachment).

when I already trained the data, it was broken to predict some data.
The Log is:
[08:52:20] Allocated 3MB on [0] GeForce GTX 1080, 4320MB remaining.
Accuracy: 84.08%
训练模型完成
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  /home/chris/Downloads/xgboost/src/predictor/gpu_predictor.cu(322): unspecified launch failure

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

I try to google the error information, but get nothing. I don't know how to do. Pls get me tips to solve this problem. Thank You.

**Comment by seanxwang** [comment]
I encountered a similar issue, running on ubuntu, AWS P3, single GPU with 16G GPU memory.
It seems crash happens when GPU memory usage surges during training
terminate called after throwing an instance of 'thrust::system::system_error'  what():  /home/ubuntu/src/xgboost/src/tree/../common/device_helpers.cuh(456): out of memory

In another issue trail, I read "currently the GPU does not swap back to disk or main memory", @pseudotensor https://github.com/dmlc/xgboost/issues/2396

Wonder if this is known issue and if there are workarounds to GPU memory limitation issue, or anything on the roadmap?

The issue can be reproduced by running this notebook (change to use "gpu_hist")
https://github.com/fmfn/BayesianOptimization/blob/master/examples/xgboost_example.py

**Comment by seanxwang** [comment]
I found a resolution. Derived from the paper below, to match "gpu_hist", it is necessary and beneficial to reduce bin size (to 64). No more crashes!
https://arxiv.org/pdf/1706.08359.pdf
