### ISSUE TITLE
python pickling seg fault

### ISSUE THREAD

**Issue by jseabold** [dmlc/xgboost#292]
I'm about at the end of the time I can spend trying to figure this out. Parking this here in case someone else has the time/inclination to fix. Note you can pickle `clf.best_estimator_` just fine but not the whole GridSearchCV object.

```
import pickle

import xgboost as xgb

import numpy as np
from sklearn.grid_search import GridSearchCV

print("Boston Housing: regression")
print("Parameter optimization")

y = np.loadtxt("boston.target")
X = np.loadtxt("boston.data")
xgb_model = xgb.XGBRegressor()
clf = GridSearchCV(xgb_model, {'max_depth': [2, 4, 6],
                               'n_estimators': [50, 100, 200]}, verbose=1)
clf.fit(X, y)

# The sklearn API models are picklable
print("Pickling sklearn API models")
# must open in binary format to pickle
pickle.dump(clf, open("best_boston.pkl", "wb"))
```

**Comment by tqchen** [comment]
OK, with regard to saving to np.array. I think any types of buffer object in python should be fine. I replaced the BufferIO because it was not pickable in python2x. Do you have other possible suggestions?

**Comment by tqchen** [comment]
This problem is fixed in recent two commit. https://github.com/dmlc/xgboost/commit/a4de0ebcd4e5a5b699794d3b78471b44890fea53 and https://github.com/dmlc/xgboost/commit/68444a06269013efd133ee6e5535faad203110b9

It was due to  saving Booster that was not yet initialized(trained).  I also changed the buffer from np.array to bytearray

@jseabold can you check to see if these changes work for you?

**Comment by jseabold** [comment]
Ah, great. Thanks. The bytearray change was also exactly what I have locally. Will have a look at the other changes tomorrow.

**Comment by tqchen** [comment]
Thanks! It would be great if you can also contribute some examples of these to guide-python. Thanks for the proposal and PR!
