### ISSUE TITLE
Why the num_col has more than 1 column ?

### ISSUE THREAD

**Issue by loverszhaokai** [dmlc/xgboost#2946]
Run xgboost with python api.
There is **only one feature**, but the **num_col()** return **2L**,  the **feature_names** also return two values which are 'f0' and 'f1'.
Q1: **Why the num_col has more than 1 column ?**

~~~
In [39]: dm = xgb.DMatrix('test/test')
[11:26:11] 4x2 matrix with 4 entries loaded from test/test

In [40]: dm.feature
dm.feature_names  dm.feature_types

In [40]: dm.feature_names
Out[40]: ['f0', 'f1']

In [41]: cat test/test
1 1
0 0
1 1
0 0

In [43]: dm.num_col()
Out[43]: 2L
~~~

Q2: **When dump the model, it uses 'f0' as the first feature, what's the 'f1' ?**
~~~
booster[0]:
0:[f0<-9.53674e-07] yes=1,no=2,missing=1
	1:leaf=1.81818
	2:leaf=-1.81818
~~~

**Comment by khotilov** [comment]
Your data has two columns because the `dm = xgb.DMatrix('test/test')` reads your file as the libsvm format, and according to the format, it has the labels and two columns (0-based indexing). The following is an equivalent representation (when the values are explicitly specified):
```
1 1:1
0 0:1
1 1:1
0 0:1
```
If your intent was to read data as csv, with the 1st column being labels, then do use comma as a separator
```
1,1
0,0
1,1
0,0
```
and specify the csv parser for DMatrix in file's URI:
```python
In [7]: dm = xgb.DMatrix('test?format=csv&label_column=0')
[13:04:33] 4x1 matrix with 4 entries loaded from test?format=csv&label_column=0

In [8]: dm.get_label()
Out[8]: array([ 1.,  0.,  1.,  0.], dtype=float32)
```
