### ISSUE TITLE
In python module tests paths to the data should be determined relative to __file__

### ISSUE THREAD

**Issue by KOLANICH** [dmlc/xgboost#2973]
Now they are just the paths relative to the current directory which makes a one who wanna run the tests to go to the main repo directory first and run the tests from it. It's better to
```python
import os
currentDir=os.path.dirname(__file__)
mainDir=os.path.join(currentDir, "..", "..")
```
and then compute data paths relative to the main dir

**Comment by KOLANICH** [comment]
???

**Comment by tqchen** [comment]
The testcase structure is quite common in python and I think we will keep it as it is. We are sorry for the massive close the issues. The main goal is to minimize the amount of issues so that actually the developer can take action on them. Please feel free to open new issues when you think is useful. 
The discussions are now welcomed at https://discuss.xgboost.ai/

**Comment by hcho3** [comment]
> Bulk closing issues is a sign of disrespect to the people who have spent own time to write an issue to improve the project a bit.

Letting a long list of issues rot without any response is also a sign of disrespect. Yes, bulk closing was not quite ideal, but we maintainers feel that having a short, organized list of issues that are actionable would help everyone coordinate efforts.

> bulk closing issues even with code and proposals on improvement

We will re-open issues containing bug reports. As for feature requests, we plan to maintain a single list of feature requests (#3439) so that potential contributors could easily find them.
