### ISSUE TITLE
[python-package] Looking for Document about feature_type When Create DMatrix

### ISSUE THREAD

**Issue by NeilRon** [dmlc/xgboost#3191]
I'm confused about feature_type format when creating DMatrix and whether the parameter is what I need.

I was using some **one-hot encoding** to transform categorical features to numerical features. But I found the transformed value is not treat as a categorical feature. 

For example, my f0 feature is "gender=male", the possible value is 0 or 1. Then I get the model dump and find some nodes "0:[f0<2] yes=1,no=2,missing=2". It's a **useless** value because both 0 and 1 is less than 2.

```
f0    gender=male    [0|1]
node    0:[f0<2] yes=1,no=2,missing=2
```

So I am considering if I need to tell XGBoost the feature 0 is a categorical or binary feature And then it would do something different. 

Appreciate your help.

**Comment by hcho3** [comment]
> It's a useless value because both 0 and 1 is less than 2.

It is still useful because the split differentiates between non-missing values and missing values. Note that 0 is treated differently than a missing value.

XGBoost treats all values as real-number, hence the need for one-hot encoding. Feel free to post additional questions at https://discuss.xgboost.ai/.
