### ISSUE TITLE
[jvm-packages] Running several distributed trainings in the same spark context in scala

### ISSUE THREAD

**Issue by yvirin-apixio** [dmlc/xgboost#3288]
From the code it seems like there is a rabit tracker which manages the communication between different partitions while training. And it seems like there is no mechanism to exactly identify the nodes and communicate to the right ones, in case that several distributed trainings are happening at once in the same cluster/spark context.

Is that the case, or I am missing something? Is there a way to run several distributed trainings. In my case I do have a large cluster but for some classifiers I do not have enough data, so I want to run them with a smaller number of partitions, presumably that due to approximations done in each partition otherwise performance would be hurt(if I partition even a small dataset to may partitions).

Also, is there any documentation on how distributed training works in details? Seems like all details are hidden in C++ code?

**Comment by yvirin-apixio** [comment]
@CodingCat May be someone can comment on that?

**Comment by CodingCat** [comment]
supposedly, when you run multiple trainings, you need to start multiple trackers, so the workers will only contact the tracker which is associated with them 

the block here is that there is some kind of race condition (or other bugs) in rabit preventing we start too many trackers in the same process space at the same time, the application will fail due to some mysterious issue

**Comment by hcho3** [comment]
You may want to read the [XGBoost paper](https://arxiv.org/pdf/1603.02754.pdf), which was published in KDD 2016.

Any future discussions are welcome at the user forum https://discuss.xgboost.ai/.
