### ISSUE TITLE
[jvm-package] How to get the record count number of each leaves in a well trained model?

### ISSUE THREAD

**Issue by USCYuandaDu** [dmlc/xgboost#3419]
Hi all!

I want to know whether we could get the number of data in leaves nodes after training.
After training, we could get a model which contains a certain number of decision trees. And for each leaf node of each tree, I want to know how many data were split into that leaves nodes. If xgboost doesn't have this function, I want to know will the committer accept it if I contribute to the committee.   

Thank you!
Bests,
Yuanda

**Comment by ywskycn** [comment]
cc @tqchen @CodingCat

**Comment by hcho3** [comment]
Currently, XGBoost model embeds Hessian statistics at leaf nodes but not data counts. Since the leaf data counts are already known at the time of training, we could potentially embed that information inside the XGBoost model. I think the leaf_vector_ field in the tree model struct is unused. We can use it to store leaf node counts

**Comment by USCYuandaDu** [comment]
@hcho3  Sounds great! I'll have a look and give it a shot if this could work.

**Comment by hcho3** [comment]
Consolidating to #3439. A new issue should be opened if someone decides to actively work on implementing this feature.
