### ISSUE TITLE
[jvm-packages] Getting Group For Custom Rank Objective and Eval

### ISSUE THREAD

**Issue by Helw150** [dmlc/xgboost#3513]
( Also posted in discuss.xgboost.ai but traffic there seems much lower - https://discuss.xgboost.ai/t/jvm-packages-getting-group-for-custom-rank-objective-and-eval/89/2 )

I’m in the process of researching moving off of a fork of XGboost to try and move onto vanilla XGboost. The primary thing that is holding me up is that in this fork a getter has been added to Scala DMatrix so that the custom objectives function and eval functions can use group info in their calculations. In the C-code for pairwise ranking, the group is accessed by a pointer, but there doesn’t seem to be a way to get group info from the Scala DMatrix.

Is there a canonical way to get group info from a DMatrix in the Scala wrapper of XGboost that I am missing? Alternatively, would the DMLC team be open to a PR which exposes this functionality?

**Comment by hcho3** [comment]
@Helw150 I left my answer in the forum post.

> traffic there seems much lower

We recently began the process of transitioning to a system where discussions and questions are hosted in the user forum. This is so that the issue tracker is kept for bug reports and feature additions. (Previously, the issue tracker was overwhelmed with unanswered questions, and it was hard to keep track of existing bugs.) We maintainers plan to watch the forum closely.
