### ISSUE TITLE
Error using in Multi-Softmax option

### ISSUE THREAD

**Issue by saj1919** [dmlc/xgboost#354]
`text_clf = XGBClassifier(n_estimators=1000,objective="multi:softmax",base_score=2.5)`
Gave me following error -
`must set num_class to use softmax`

So I added parameter.
`text_clf = XGBClassifier(n_estimators=1000,objective="multi:softmax",num_class=4,base_score=2.5)`

Which gives me following error - 

Traceback (most recent call last):
`
  File "/home/saj1919/workspace/ML_LEARN/kaggle/search_relevance/src/analyze.py", line 402, in <module>
    aobj.pickle_model(query)
  File "/home/saj1919/workspace/ML_LEARN/kaggle/search_relevance/src/analyze.py", line 181, in pickle_model
    text_clf = XGBClassifier(n_estimators=1000,objective="multi:softmax",num_class=4,base_score=2.5)
TypeError: __init__() got an unexpected keyword argument 'num_class'
`
Can you please tell me it is the right way of using num_class parameter ?
_I am using python xgb._

**Comment by tqchen** [comment]
I think in sklearn wrapper this is n_classes

**Comment by drag0** [comment]
@tqchen - I tried n_classes and it failed. Did it change?

**Comment by johnsonlui** [comment]
It seems n_classes is not work

**Comment by pmbaumgartner** [comment]
I haven't validated, but it looks like multiclass predictions happen automatically with `XGBClassifier` if you pass it a `y` vector with more than one class. See the code starting at: https://github.com/dmlc/xgboost/blob/37bc122c90b7c1337403f797fb7b01fc6abd5b36/python-package/xgboost/sklearn.py#L393

Would be nice to verify though, especially since the docs state:
> “multi:softmax” –set XGBoost to do multiclass classification using the softmax objective, you also need to set num_class(number of classes)
