### ISSUE TITLE
XGBRegressor fails check_estimator function of sklearn

### ISSUE THREAD

**Issue by cyrust** [dmlc/xgboost#3580]
sklearn has a check_estimator function to test if estimators are written properly and follow sklearn convention. I tried it on XGBRegressor and it failed.

Attempting to run
`
from sklearn.utils.estimator_checks import check_estimator

print(check_estimator(XGBRegressor))
`
raises,
> xgboost.core.XGBoostError: need to call fit beforehand

It would be nice if it was possible to comply with sklearn's recommended checks. Does anyone know of a quick fix to this? It might not be too bad.
The check that fails is 

> check_no_fit_attributes_set_in_init

with comments within it stating
`            # This check is for properties, they can be listed in dir
            # while at the same time have hasattr return False as long
            # as the property getter raises an AttributeError`

**Comment by cyrust** [comment]
I'll try to have a look at it.

**Comment by hcho3** [comment]
@cyrust I looked at this and I don't think it is possible to pass the test [`check_estimators_nan_inf()`](https://github.com/scikit-learn/scikit-learn/blob/f0ab589f1541b1ca4570177d93fd7979613497e3/sklearn/utils/estimator_checks.py#L868-L902) since XGBoost explicitly allows NaN as missing value. One of major advantage of XGBoost over scikit-learn algorithms is that XGBoost handles missing values naturally as part of the training stage, whereas you need to perform imputation for scikit-learn.

**Comment by hcho3** [comment]
@cyrust I added a few test anyway, even though it's not possible to pass check_estimator() because of the NaN issue mentioned earlier.
