### ISSUE TITLE
Use -march=native and -mtune=native

### ISSUE THREAD

**Issue by KOLANICH** [dmlc/xgboost#3772]
These gcc flags instruct the compiler to optimize the library for the CPU build is run on. It would be nice to reflect them in CMake scripts as binary variables to allow a user to select them by clicking in GUI.

UPD: `-march=native` results into a python interpreter crash on Windows.

**Comment by trivialfis** [comment]
> allow a user to select them by clicking in GUI.

I don't think it's a good practice to add compiler optimization flags to a generic build system (CMake).

>  results into a python interpreter crash on Windows.

For starter, it's best to build everything with same version of the same compiler using same optimization flags, c/c++ don't have standard binary interface.  I don't know how cpython blob and many others are built on windows.

And, yes `-march-native` causing trouble happens a lot.

I'm closing this for now, feel free to reopen if you feel needed.

**Comment by hcho3** [comment]
@trivialfis FYI, the OP was using MinGW to compile XGBoost, whereas Python on Windows is built with Visual Studio. The runtime incompatibility leads to crashes.

> it's a good practice to add compiler optimization flags to a generic build system

This is a problem though, since we may want to consider adding `O3` for performance reasons. A guy I know ran experiments with hcho3/xgboost-fast-hist-perf-lab and he noticed significant difference in performance when he added `O3`. I do agree that `march=native` is dangerous territory. I certainly won't use it when building binary wheels.

**Comment by trivialfis** [comment]
@hcho3 I think this might be a better a quote :) 

> I **don't** think it's a good practice to add compiler optimization flags to a generic build system

A solution might be `Function multi-versioning (FMV)`, but I don't think we have the resource to make sound maintenance on such a thing, at least not now.
Since we are using GCC-4.8 to build the wheel, I assume the major concern in binary wheel is convenience not performance.  So lets just leave it to users to decide how they want to balance these things.   If your benchmark shows the difference is that significant, we can always document it in the installation note.

**Comment by hcho3** [comment]
Oops sorry for the mis-quote :)

I think it's useful to distinguish two kinds of optimizations: machine-independent and machine-dependent. In my opinion, machine-independent optimization flags (`-O3`, `-funroll-loops` etc) should be part of CMakeLists.txt and also be applied to wheel building. 

On the other hand, machine-dependent flags (`-msse`, `march=native`) result in non-portable binaries and thus shouldn't be part of the default setting. Also wheels cannot make use of these flags. To use these settings, the user can always set `CFLAGS` and compile from source.

I took a look at FMV and it looks like an interesting concept, similar to CUDA fat binaries that target multiple architectures simultaneously. Unfortunately, FMV seems to have limitation and also as you say increases maintenance burdens.

**Comment by hcho3** [comment]
And yes, the point of using binary wheels is convenience. You will always want to compile from source for maximum performance.

**Comment by KOLANICH** [comment]
>I don't think it's a good practice to add compiler optimization flags to a generic build system (CMake).

In fact it is the only possible way in CMake other than writing a script abstracting that out and moving that all into confing for a very minor profit. In fact `-O3` for `Release` [is also hardcoded](https://github.com/Kitware/CMake/blob/b11e021bed6d406e3a7b9af6f5ef8fa5565881af/Modules/Compiler/GNU.cmake#L46) into CMake.

So what in fact we need is a CMake module creating a unified interface suitable for all the supported compilers for this and some other flags.

>it's best to build everything with same version of the same compiler using same optimization flags

It should be possible to build with CLang using MS runtime libs without resulting in a crash, but I have not tried this way since it requires MSVC.

**Comment by hcho3** [comment]
@KOLANICH @trivialfis A CMake module for compiler flags looks like a reasonable compromise. Enable safe flags like `O3` by default, and also let users explicitly turn on unsafe flags.

**Comment by trivialfis** [comment]
@KOLANICH @hcho3 

> In fact it is the only possible way in CMake

From a user's perspective, optimization flags for CMake can be appended as `cmake -DCMAKE_CXX_FLAGS="..." ../xgboost`.

If we were to add these flags as options for the benefit of GUI, we need to think about different compilers with different platforms with different runtimes of language bindings, since adding it means we are supporting/maintaining it.  I still believe if such a functionality should exist, it should be implemented in CMake, not down stream projects like XGBoost, since we don't want to maintain the effect for each different compiler.  Even it's implemented in CMake, problem from dependencies is not solved.

> A CMake module for compiler flags looks like a reasonable compromise.

If I were to implement such a module, I will send it directly to the CMake project, and later upgrade the dependency of XGBoost.

> In fact -O3 for Release is also hardcoded into CMake

> t should be possible to build with CLang using MS runtime

These are not guaranteed behaviours, it can break easily. :(  Or worse, it already breaks somehow but we fail to notice.

> Enable safe flags like O3 by default,
`O3` is not a safe flag, it's an "aggressive" flag, we don't have a level higher than 3. The majority of Linux distribution is still on `O2` except the ones like clear Linux where a huge amount of expertise is put into maintaining it. And I had personal experience with `O3` breaking `GMP (GNU Multiple Precision)` program.

So, the question is, is this a problem should be solved by XGBoost? :)

**Comment by hcho3** [comment]
> we don't have a level higher than 3.

Not really, since there is `-Ofast`. Well, it looks like `O3` also has possibility of breaking things. I'll take your word for this.

> we need to think about different compilers with different platforms with different runtimes of language bindings, since adding it means we are supporting/maintaining it

Yeah, good point about maintenance burden. I'm going to scrap the idea of CMake module. We'll just set `O2` for gcc/clang compilers and call it a day. Users can always manually set flags themselves.

As for benchmark purposes, we should create a document describing some flags people can try out. In particular, SSE and AVX have potentials for improving performances.

**Comment by trivialfis** [comment]
> Not really, since there is -Ofast
Oops, I totally missed that, thanks. Reading the man page from GCC, this option disregard strict standards compliance.

>  SSE and AVX have potentials for improving performances.
It would be interesting to benchmark these stuffs, there are some others worth trying like link time optimization.

**Comment by hcho3** [comment]
@trivialfis It turns out XGBoost already uses O3 because CMake is set to
Release configuration.
