### ISSUE TITLE
why does PairwiseRankObj not have GetLambdaWeight function implement?

### ISSUE THREAD

**Issue by poryfly** [dmlc/xgboost#3779]
why does PairwiseRankObj not have GetLambdaWeight function implement?

**Comment by hcho3** [comment]
This is because `GetLambdaWeight()` contains details that are specific to listwise ranking. Since `PairwiseRankObj` performs pairwise ranking, it does not implement `GetLambdaWeight()`. See https://www.microsoft.com/en-us/research/publication/from-ranknet-to-lambdarank-to-lambdamart-an-overview/ for more details.
