### ISSUE TITLE
Document use of external memory Spark/JVM

### ISSUE THREAD

**Issue by thvasilo** [dmlc/xgboost#4082]
I was helping out a user [in the forum](https://discuss.xgboost.ai/t/jvm-packages-xgboost4j-external-memory-explain/594), and I found out about the [useExternalMemory](https://github.com/dmlc/xgboost/blob/4fac9874e0abcf864a9ca00f66ccb65bcdd86696/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostRegressor.scala#L268) parameter that, as far as I can understand, will make use of the out-of-core algorithm.

I'm a bit confused about the purpose of this parameter vs. [the examples](https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-example/src/main/scala/ml/dmlc/xgboost4j/scala/example/ExternalMemory.scala) we have for how to use external memory, i.e. changing the input data path.

Is the effect of these two the same? We might want to document this in that case.

**Comment by trivialfis** [comment]
Hopefully I can find the time to fix external memory soon.  #4037

**Comment by hcho3** [comment]
@thvasilo `useExternalMemory` is needed for XGBoost4J-Spark, since you are not reading from a text input. Here is the documentation: https://xgboost.readthedocs.io/en/latest/jvm/scaladocs/xgboost4j-spark/index.html#ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier@useExternalMemory:org.apache.spark.ml.param.BooleanParam
