### ISSUE TITLE
Parallel lost after update

### ISSUE THREAD

**Issue by phahn57** [dmlc/xgboost#4320]
Just updated XGBoost from 06.xx to 08.62.1
Lost parallel working. Before worked fine, because of an issue with prediction did the update.
My computer
R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.2

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] de_DE.UTF-8/de_DE.UTF-8/de_DE.UTF-8/C/de_DE.UTF-8/de_DE.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3    yaml_2.1.16

**Comment by hcho3** [comment]
“Lost parallel working”

Can you be more specific?

**Comment by phahn57** [comment]
Normally I work on my MacBook. Because I am not able to install openMP, I today used my iMac. When I build a model with "old" version I had all 4 cores running parallel, but when I finished calculation prediction was not possible for gblinear. Thus I updated XGBoost from within Rstudio. Next run of modeling is still running :-(. It is now late in the evening, have to look after it tomorrow evening. 
BTW: any tips how to install OpenMP on a new MacBook ? Tried it today several times, took about 3 hours without success. My Macbook has a 6 core processor (2018), my iMac only 4 cores (2013).
Peter

**Comment by hcho3** [comment]
@phahn57 The issue is that the default compiler on Macbook doesn't support OpenMP. To enable OpenMP, you should use Homebrew GCC compiler instead.

Follow these steps on your Macbook (tested on my Macbook Pro):

1. Install Homebrew from https://brew.sh/.
2. In the command line, run `brew update`.
3. Install Homebrew GCC by running `brew install gcc@8`.
4. Install CMake by running `brew install cmake`
4. Now download code for XGBoost 0.82: `git clone --recursive https://github.com/dmlc/xgboost -b release_0.82`.
5. Compile XGBoost with the following commands:
```
cd xgboost
mkdir build
cd build
CC=gcc-8 CXX=g++-8 cmake .. -DR_LIB=ON
make -j$(nproc) install
```
Now you should have access to XGBoost from the Rstudio. This time, you should be able to use all cores on your machine.

**Comment by phahn57** [comment]
Thanks. Amazing fast
