### ISSUE TITLE
xgb.cv is needs to be  restructured for proper time-series cross validation

### ISSUE THREAD

**Issue by Sustainabilist** [dmlc/xgboost#4373]
In the xgb.cv function, there is a feature which allows for custom folds, but this feature is improperly structured for time-series cross-validation methods. Specifically, because the folds vectors only indicate test-folds, it seems that all other data becomes training data, thus negating the ability to exclude data-points that occur chronologically after the test folds from the training set. 

This is problematic for rolling-window and rolling origin CV, common time-series methods.

There appear to be two options:

1. Alter the xgb.cv method to include the ability to denote both test and training indices. 
2. Create a second function, xgb.cv.ts, which serves to be the home of all time-series based cross-validation methods for xgboost. 

Option (2) seems to be more practical, but I will await the input of the community before beginning work on either option.

**Comment by hcho3** [comment]
@Sustainabilist I am not an expert in time series analysis. I recall that the theory behind XGBoost makes an i.i.d. assumption, and many time-series data will violate i.i.d. due to auto-correlation. I'm not sure how well XGBoost works for time-series analysis, and I am not sure whether XGBoost should support features that are specific to times series.
