### ISSUE TITLE
Request: Please add RMLSE eval_metric

### ISSUE THREAD

**Issue by flyingdisc** [dmlc/xgboost#446]
Many Kaggle's competitions use RMLSE, thank you.

**Comment by hetong007** [comment]
There're two ways to achieve it on user's side:

1. Make RMSE prediction on the transformed predict variable `log(1+y)` instead of `y`.
2. Customize the objective in [R](https://github.com/dmlc/xgboost/blob/master/R-package/demo/custom_objective.R) or [Python](https://github.com/dmlc/xgboost/blob/master/demo/guide-python/custom_objective.py).

The first one is the simplest.

**Comment by gtesei** [comment]
Hi guys, I recently customized in R RMLSE for Xgboost. I used it in a recent Kaggle competition with pretty good results. Here's the [code](https://github.com/gtesei/fast-furious/blob/master/R-package/R/fastRegression.R). Functions involved: **RMSLE.xgb** / **xgb_cross_val** / **xgb_train_and_predict**. Of course, it is possible to adopt other approaches to get the best nrounds.     

**Notice 1**:   Although they work in local, I disabled testthat tests for Xgboost as they don't terminate on Travis. I'm currently working on the issue.  So, this code is not currently covered by tests. 

**Notice 2**: this part of the project (the R-package) is currently in development & undocumented.
