### ISSUE TITLE
reason to use float to hold eval metric?

### ISSUE THREAD

**Issue by CodingCat** [dmlc/xgboost#4665]
is there a particular reason to use float to hold eval results instead of double (saving memory?)?

I asked because I recently met a case that 6 digits after decimal is way too aggressive to determine it is time to `early stop`

**Comment by hcho3** [comment]
Which metric were you using? BTW, I think certain metrics are not quite exact in distributed setting, see #4663, so I'm not sure it's worthwhile to use double precision.

**Comment by CodingCat** [comment]
@hcho3 I am using logloss

**Comment by hcho3** [comment]
Was your dataset pretty big?

**Comment by CodingCat** [comment]
big and unbalanced

**Comment by gorkemozkaya** [comment]
I can confirm me and my teammates have been affected by this issue. What is confusing is, even if it is using a float variable, it should be able to hold small values up to 1e-45. The current object seems not to be able to hold values smaller than 1e-6. 

```
[320]	train-rmse:0.000028
[321]	train-rmse:0.000028
[322]	train-rmse:0.000028
[323]	train-rmse:0.000028
```

**Comment by RAMitchell** [comment]
Looks like floating point error is accumulating in the sum. Look at https://github.com/dmlc/xgboost/blob/0e0955a6d83d35a32cbf3ddfaf6893171d1168ea/src/metric/elementwise_metric.cu#L45

The accumulator variable is a float32. You might be able to improve the accuracy significantly just by changing some of these intermediate variables to doubles.

**Comment by gorkemozkaya** [comment]
But even with float32's, we should be able to have precision up to 1e-45. Currently, we seem to have a mysterious limit of 1e-6, and it is affecting not only the evaluation metric but also the objective. Here is a notebook that demonstrates this. Simply scaling the label array by 1e-10, the trained trees become root-only trees, and the eval metric goes down to 0: https://nbviewer.jupyter.org/github/gorkemozkaya/ds_debugging/blob/master/Precision%20issue%20of%20XGBoost.ipynb

**Comment by RAMitchell** [comment]
Precision is not the same thing as the smallest possible value representable in float32. My point still stands, precision is being lost in intermediate calculations.

**Comment by RAMitchell** [comment]
I looked a bit more closely, the digits past six are lost because xgboosts c_api returns a string to a fixed precision (https://github.com/dmlc/xgboost/blob/57106a345960d31c4f6df74912c1f0b7e2fa95b5/src/learner.cc#L451).

There are a couple of options for a fix:
- Simply output the string at full precision (https://stackoverflow.com/questions/54370268/java-style-printing-of-double-in-c). This may be significantly less readable as the text will not be aligned when printing out eval metrics
- Return floating point numbers directly from the C API and let the language bindings format the output when it comes to printing them. This way the early stopping mechanism in the language bindings can compare the metrics at full precision.

Probably we would have to do option 2 but it needs a bunch of refactoring.

**Comment by hcho3** [comment]
@RAMitchell Indeed, the ideal method is to return structured data for metrics instead of returning a formatted string. Currently, Python and R wrappers parse the formatted string to extract individual metrics, essentially performing a round trip.

**Comment by RAMitchell** [comment]
I like the JSON idea.

**Comment by trivialfis** [comment]
What's the difference between passing json instead of plain float?

**Comment by hcho3** [comment]
@trivialfis The issue is that we have a key-value pair representing metrics and their name, e.g.
```
{ 'train-rmse': 0.35, 'test-rmse': 0.22 }
```
This is a perfect fit for JSON.

Currently, `XGBoosterEvalOneIter()` simply returns a string like
```
[0] train-rmse: 0.350000, test-rmse: 0.2200000
```
and the Python wrapper parses the string. IMHO, this feels like an ad-hoc representation of key-value data, and we're better off using JSON.

**Comment by trivialfis** [comment]
Thanks for the explanation, can we make changes to R, Julia and Ruby bindings?  I can handle the others ...
________________________________

**Comment by hcho3** [comment]
@trivialfis Let us create a new function `XGBoosterEvalOneIterEx()` that returns JSON, and then we can modify all bindings to replace `XGBoosterEvalOneIter()` with `XGBoosterEvalOneIterEx()`. We will then deprecate the old function `XGBoosterEvalOneIter()`. What do you think?

**Comment by trivialfis** [comment]
Sounds good.  It's on my to-do list now.  May not be able to get to it until finishing existing PRs.
________________________________

**Comment by trivialfis** [comment]
Another thing is, we might be able to handle early stoping inside c++.  If we do it this way we can handle the memory releasing issue.  Just something to think about.
________________________________

**Comment by hcho3** [comment]
> Another thing is, we might be able to handle early stoping inside c++.  If we do it this way we can handle the memory releasing issue.  Just something to think about.

Let's discuss this in a separate RFC.
