### ISSUE TITLE
Use bundled gtest in all CI scripts

### ISSUE THREAD

**Issue by trams** [dmlc/xgboost#4675]
XGBoost native part uses Google Test Framework for tests

and there has been implemented USE_DMLC_GTEST CMake option to reuse gtest bundled with DMLC and I like this option! After discovering it I had my tests run on Windows|Linux without any problem

I suggest to
- [x] Remove "EXPERIMENTAL" from option description and update the doc for contributors with suggestion to use it
- [x] Make sure this option leads to us using the fixed released version of gtest
- [x] Move all CI scripts to use this option for tests

Now I saw that
1. build_via_cmake.sh uses 1.7
2. clang_tidy.sh use 1.8.1

I can prepare the pull request but first I want to ask community:
1. Is it a sensible proposition?
2. Do I miss something?

Thank you

**Comment by hcho3** [comment]
@trams I added USE_DMLC_GTEST because I could not get Google Test working otherwise on Windows. Now that it's been in use in the automated testing server (https://xgboost-ci.net) for a while, I think it's safe to remove the EXPERIMENTAL label.

As for the version of Google Test, I think we need 1.8.1 or newer for Clang-tidy. So I suppose we should use 1.8.1 everywhere for the sake of consistency.

**Comment by trams** [comment]
Thank you for the context

**Comment by hcho3** [comment]
Let's update the doc after dmlc/dmlc-core#542 is merged.

**Comment by trams** [comment]
Given dmlc submodule has been updated to point to a version which included
https://github.com/dmlc/dmlc-core/commit/26575157860f86c8abd854fa2f1b10cb9934cc49
I resumed the work on using bundled with dmlc googletest consistently though all the code

Here is my pull request https://github.com/dmlc/xgboost/pull/4900

**Comment by hcho3** [comment]
Fixed in #4900
