### ISSUE TITLE
Remove Makefile based build system

### ISSUE THREAD

**Issue by codingforfun** [dmlc/xgboost#4899]
Is there a valid reason to keep the Makefiles? They seam to be historic and nowadays everythings is build using CMake. Correct me if I missed something.

**Comment by trivialfis** [comment]
R package for cran...

**Comment by trivialfis** [comment]
@codingforfun Feel free to reopen if you have experience on getting CMake to pass cran build.

**Comment by hcho3** [comment]
@trivialfis @codingforfun The issue is that R packaging system is stuck using Makefile as build system. We can try to call CMake from the Makefile; however, not every target required by the CRAN policy (see the list [here](https://cran.r-project.org/web/checks/check_results_xgboost.html)) appears to have CMake installed.

**Comment by codingforfun** [comment]
Ok. I understand. I missed that. Sorry for the noice.

**Comment by hcho3** [comment]
#5513 removes Makefile completely, except for convenience tasks.
