### ISSUE TITLE
Threshold effect due to multiple cut point strategies in histogram mode

### ISSUE THREAD

**Issue by DoanHuuJacques** [dmlc/xgboost#5095]
Hi,

looking at AddCutPoint() method, I noticed a heuristic with size threshold (16) which determines the strategy to define cut point values.
Is there a particular reason (except to avoid division operations and to be a bit faster) to not always consider the mid-point strategy even for large cardinality?

Indeed, when I encode my categorical features based on the category frequency, if the cardinality is greater than 16, the last 2 categories (most frequent ones) and the first 2 categories cannot be split. The consequence is that if 2 categories at extreme boundaries are significantly discriminative to improve the model accuracy, the split cannot occur between them.
Such issue is more effective with frequency encoding as most frequent categories are placed at the upper boundary.

Thanks a lot for clarification.
Regards

Jacques

void AddCutPoint(WXQSketch::SummaryContainer const& summary) {
    if (summary.size > 1 && summary.size <= 16) {
      /* specialized code categorial / ordinal data -- use midpoints */
      for (size_t i = 1; i < summary.size; ++i) {
        bst_float cpt = (summary.data[i].value + summary.data[i - 1].value) / 2.0f;
        if (i == 1 || cpt > p_cuts_->cut_values_.back()) {
          p_cuts_->cut_values_.push_back(cpt);
        }
      }
    } else {
      for (size_t i = 2; i < summary.size; ++i) {
        bst_float cpt = summary.data[i - 1].value;
        if (i == 2 || cpt > p_cuts_->cut_values_.back()) {
          p_cuts_->cut_values_.push_back(cpt);
        }
      }
    }
  }

**Comment by trivialfis** [comment]
@hcho3

**Comment by hcho3** [comment]
> Is there a particular reason (except to avoid division operations and to be a bit faster) to not always consider the mid-point strategy even for large cardinality?

The cut point is part of a quantile sketch, so it represents an estimate of quantile value. The midpoint strategy introduces bias by shifting the estimate upward. The shifting is done for categorical or binary features because often a quantile estimate coincides with another integer feature value, so shifting is necessary to discriminate between two adjacent discrete feature values.

The number 16 was chosen as a trade-off: if we enable the midpoint strategy for all cases, we would affect splits for continuous features and thus incur significant bias. And currently we don’t have a good way to distinguish between discrete and continuous feature columns, so hence the heuristic. Perhaps letting the user explicitly list discrete features will address the issue better.

**Comment by DoanHuuJacques** [comment]
@hcho3 
Hi Philip
thanks for the quick clarification.
As XGBoost copes only with numerical values requiring upfront encoding into numbers, discrete and continuous are indistinguishable.
I understand now why 2 cut point strategies are available depending on the discrete nature of the feature.
It would be great to explicit such metadata (categorical vs continuous) per feature in a future release, in order to trigger the proper cut point strategy  instead of relying on hard-coded cardinality threshold.
Indeed, it's quite common to deal with pretty high cardinality for discrete features.

Should I create a particular ticket for such improvement track? 
Thanks

**Comment by trivialfis** [comment]
Yes.  Please open an issue for that, as collecting insights helps later implementation.

**Comment by DoanHuuJacques** [comment]
@trivialfis 
I will do thanks
