### ISSUE TITLE
python-package installs xgboost/libxgboost.so again when it is already installed

### ISSUE THREAD

**Issue by yurivict** [dmlc/xgboost#5118]
The ```xgboost``` package installed ```lib/libxgboost.so```.

**Comment by hcho3** [comment]
Please provide additional details: how did you install xgboost?

**Comment by yurivict** [comment]
I installed xgboost using cmake/gmake.

**Comment by hcho3** [comment]
This is expected behavior, so that Python interpreter may locate `libxgboost.so` when you run `import xgboost` inside a Python session.

**Comment by yurivict** [comment]
It installs the copy of its dependency into /usr/local again which pollutes the system with duplicates.

**Comment by hcho3** [comment]
That is odd. I have not seen that behavior before. For the three OSes we officially support (Linux, Mac, Windows), the library file gets installed under Python `site-packages`.

**Comment by hcho3** [comment]
> ... which pollutes the system with duplicates.

For the record: Duplication happens when XGBoost is compiled from the source and installed with `make install`. Since most users download pre-built binaries from PyPI, this problem did not surface before.

**Comment by yurivict** [comment]
FYI: Python finds the dependency .so library fine in it original location under /usr/local/lib, there's no need to copy it at all.

**Comment by hcho3** [comment]
@yurivict Good point. However, it’s only applicable when the user compiles from the source and runs `make install`. If the user installs stable version with `pip install xgboost` (and he is using Linux), then there would be no `/usr/local/lib/libxgboost.so`.

Let me think about this more.

**Comment by trivialfis** [comment]
I recently looked into our `setup.py`.  It's seems quite messy to refactor it.  To make things nice for everyone, here are the things we need to understand:

- python setup.py bdist
- python setup.py bdist_wheel
- python setup.py sdist
- python setup.py install
- python setup.py build_ext
- Installation with libxgboost.so in system path instead of python site-package

....

I would really appreciate some helps from others who are familiar with the internal of setuptools.

**Comment by hcho3** [comment]
Closing this, since we've now refactored `setup.py` to install `libxgboost.so` under the Python installation path and not `/usr/local/lib/`.
