### ISSUE TITLE
Xgboost and scipy sparse matrix not compatible

### ISSUE THREAD

**Issue by Seanspt** [dmlc/xgboost#5136]
While xgboost apis accept scipy sparse matrix,
they are not compatible for scipy always treats `zero` as missing value, while xgboost may take `NaN` as missing value.

If you get a sample like `[NaN, 0.0, 1.0]`. To construct a sparse matrix from that sample, `NaN` is treated as a normal float and `0.0` as missing value for scipy. 

Then you may get different result for `xgb_model.predict_proba(sparse_matrix)` and `xgb_model.predict_proba(sparse_matrix.todense())`.

The problem is that when deal with `xgb_model.predict_proba(sparse_matrix)`, xgboot take the sample as `[NaN, NaN, 1.0]` internally. 

The same problem happens when xgb_model.predict_proba fed with a python list, which will be converted to a sparse matrix.

**Comment by hcho3** [comment]
@Seanspt I do not think the problem has to do with XGBoost. As you pointed out, SciPy always treats 0.0 as missing value.

> To construct a sparse matrix from that sample, NaN is treated as a normal float and 0.0 as missing value for scipy.

In this case, the way to handle missing value correctly is to replace all NaN's with 0.0 prior to converting to SciPy sparse matrix. Then, when you construct `xgboost.DMatrix` object, make sure to pass `missing=0` argument, so that XGBoost will treat 0.0 as missing. The idea is to **use only one and only one representation for the missing value**.

In your use case, should both NaN and 0 be considered as missing?

**Comment by Seanspt** [comment]
Thanks for the quick reply. 

Agree with that no problem with xgboost.  It's more related to  the limitation of scipy matrix to represent missing values. 

In some cases, `zeros` are meaningful, like income or profit, while `nones` means that we don't know the actual value. 

Things may go wrong for users not digging into the details. So just point that out and leave a record here.

Close the issue then.

**Comment by hcho3** [comment]
Yeah, in cases where 0 is a meaningful value, SciPy will give you trouble.
