### ISSUE TITLE
Parameter names aren't validated

### ISSUE THREAD

**Issue by Kodiologist** [dmlc/xgboost#5568]
With the latest XGBoost (9c1103e06cf72de4f02a0f3ed9a8c5691e91e748) on R, no error or warning seems to be produced for unrecognized parameter names, despite #5157.

```
> library(xgboost)
> m = xgboost(params = list(gama = 2), nrounds = 10, data = as.matrix(mtcars[, c("disp", "hp", "drat")]), label = mtcars$mpg)
```

**Comment by trivialfis** [comment]
I'm enabling parameter validation case by case, only went through 2 Python interfaces (normal `train` and `scikit-learn`).  You can try to set `validate_parameters` to `TRUE` on R to see if it helps.

Will test through R package for validation as the next step, just being careful so that users won't silent XGBoost due to false alarms.

**Comment by Kodiologist** [comment]
`validate_parameters = TRUE` indeed prints `Parameters: { gama } might not be used`.
