### ISSUE TITLE
run XGboost via a distributed cluster of GPU backed dask workers 

### ISSUE THREAD

**Issue by sami2ahmed** [dmlc/xgboost#5691]
@trivialfis firstly, thanks for composing this article on medium on using GPUs/dask/CUDA (https://medium.com/rapids-ai/a-new-official-dask-api-for-xgboost-e8b10f3d1eb7) 

In the article you say: "This snippet [below] can scale to run on virtually any machine or cluster." 
```
if __name__ == '__main__':
    # `LocalCUDACluster` is used for assigning GPU to XGBoost 
    # processes. Here `n_workers` represents the number of GPUs 
    # since we use one GPU per worker process.
    with LocalCUDACluster(n_workers=2) as cluster:
        with Client(cluster) as client:
            main(client)
```

It's unclear to me how I might edit the snippet so that I can leverage a _distributed_ cluster of GPU backed dask workers to run computations on the GPU (i.e. not using the localcudacluster). Thanks again

**Comment by trivialfis** [comment]
Thanks for raising an issue.  The easiest way to get started is as follow, you can automate it using some tools like slurm, I will leave it to dask's document.

1. ssh to your cluster: run `dask-scheduler --scheduler-file=scheduler.json`, launching a scheduler.
2. ssh to your cluster: run `dask-cuda-worker --scheduler-file=scheduler.json`, launching a cuda worker (possibly with multiple GPUs).  The `scheduler.json` points to the same file generated by 1.
3. Repeat 2 until you finish launching all needed workers.
4. Open "scheduler.json" file, check "address" attribute, for example it might look something like `tcp://192.168.0.0:8786`.  Modify the script on line `with Client(cluster) as client:`, the `Client` class has an argument called `address`, use it.  Also it has an argument called `scheduler_file`, you can give it the path to `scheduler.json` instead of pasting `address`.

**Comment by sami2ahmed** [comment]
@trivialfis actually it looks like what I want to do is not possible based on this issue/feedback from the Dask team https://github.com/dask/dask-gateway/issues/177

**Comment by sami2ahmed** [comment]
thanks for being so responsive

**Comment by trivialfis** [comment]
You don't need that library to run this example
