### ISSUE TITLE
Investigate GPU hang on Kubeflow env.

### ISSUE THREAD

**Issue by trivialfis** [dmlc/xgboost#6636]
There's a report on GPU Hist hanging on Kubeflow environment without using dask.  I can't publish all the details yet, opening an issue as a reminder.

``` python
from sklearn.datasets import fetch_california_housing
import xgboost
data = fetch_california_housing()
X = data.data
y = data.target
param = {
    "eta": 0.05,
    "max_depth": 10,
    "tree_method": "gpu_hist",
}
dtrain = xgboost.DMatrix(X, label=y, feature_names=data.feature_names)
model = xgboost.train(param, dtrain,50)
```

**Comment by supertetelman** [comment]
For this issue the Kubeflow environment was installed following these steps: https://github.com/NVIDIA/deepops/blob/master/docs/k8s-cluster/kubeflow.md#installation

The Kubeflow environment was installed following these steps: https://github.com/NVIDIA/deepops/tree/master/docs/k8s-cluster

And this has been reproduced in several different environments on T4 and V100 GPUs running a base OS of Ubuntu 18.04.

This issue was first seen in the RAPIDS container v0.9 from NGC and was reproduced in the v0.17 container. The issue occurs in Kubeflow, but does not occur when launched directrly through Kubernetes.
