### ISSUE TITLE
Refactor setup.py

### ISSUE THREAD

**Issue by terrytangyuan** [dmlc/xgboost#684]
@phunterlau Could you combine setup.py and setup_pip.py with some conditional statement to switch the functionality? (set default to original setup.py functionality) Given recent issues we have received, it's better to make it less confusing.

**Comment by phunterlau** [comment]
`setup_pip.py` and `setup.py` were the same file with conditional statement, and later on I made a standalone `setup_pip.py` for the pip package for these three reasons after seeing many github installation issues:

1. pip uses `setup.cfg` and `MANIFEST.in` for complicated dependency while `setup.py` itself can't handle: we need to copy many source files and compile on-the-fly.
2. `python setup.py install` needs `include_package_data=True` for using `setup.py` path, while pip needs it being `False` for using `MANIFEST.in`, otherwise  the dependency can go crazy for some Linux machines, e.g. the `.so` lib would be copied to the root directory instead of `site-package`
3. There was a single `setup.py` for both installation, with `if` statement for checking if runs with pip or not, but that `if` statement stopped working when upgrade to pip 7.1.2. No clear solution for now.

I will refactor some pip installation and provide pre-compiled wheels, which can ultimately solve many issues of `no compiler installed`.

**Comment by terrytangyuan** [comment]
Ok sounds good. Thanks for the clarification!
