### ISSUE TITLE
Maven is missing some xgboost versions

### ISSUE THREAD

**Issue by jsleight** [dmlc/xgboost#7281]
Noticed that maven is missing some xgboost versions (including the latest).  [E.g., xgboost4j](https://mvnrepository.com/artifact/ml.dmlc/xgboost4j) -- xgboost4j-spark also has missing versions.  They do seem to be consistent about which versions are available.

**Comment by hcho3** [comment]
@jsleight The missing versions are missing because of one of two reasons:
1) A critical bug was found that made a particular release unsuitable for publication; or
2) A patch release was not applicable to the JVM package. For example, 1.4.2 is identical to 1.4.1 in all parts except the Python package.

**Comment by jsleight** [comment]
> A patch release was not applicable to the JVM package. For example, 1.4.2 is identical to 1.4.1 in all parts except the Python package.

In these cases it could be nice to publish anyway, even though the jar will be identical.  E.g., I manage xgboost deployments across multiple environments so have both python and jvm packages.  It is nice to have the versions be matching across all environments so I know everything is compatible.  As is I have to maintain a compatibility matrix.

**Comment by trivialfis** [comment]
Indeed we can improve this area in future releases.
