### ISSUE TITLE
How to reduce Memory usage on GPU version xgboost?

### ISSUE THREAD

**Issue by RunxingZhong** [dmlc/xgboost#7527]
Hi,

I have a machine with 512G Memory and 320G GPU Memory. (320G = 8 * 40G)

when running on GPU version xgboost setting as 
```
    'tree_method': 'gpu_hist'
```

I test it on a random data, for example:
```
    X_train = np.random.randn(1000000, 2000).astype(np.float32)
    y_train = np.random.randn(1000000).astype(np.float32)
```
Monitoring the Memory and GPU Memory usage as follow:
```
    Memory ~= 24G
    GPU memory ~= 6G
```
    
As we can see, Memory usage is about 4 times of GPU Memory usage.

While my machine only got 512G Memory and 320G GPU Memory.
When I running on a larger data that costing 300G GPU Memory, I need about 1200G Memory...
So my question is how to reduce the Memory usage on Xgboost gpu version.

1) Why running on GPU versiom xgboost, still occupying so much Memory.
2) beside, I notice that when running on gpu version, it still occupying one CPU thread with 100%. Is it exchaning data between Memory and GPU meomroy constantly?
3) I have try xgb.DataIter using external meomry, which can reduce momory on CPU version xgboost. While reporting error on GPU version xgboost. (std::bad_alloc)
4) How can I reduce Memory usage on GPU version xgboost?

I am looking forward to your reply.
Thanks!

**Comment by trivialfis** [comment]
Internally XGBoost stores the data in CSR, so a double of memory usage.  A sort is required for quantization, so a copy of the CSR (no inplace parallel sort algorithm available). ~4 times ...

If your data is loaded as GPU-based data structure like cupy, then you can use `DeviceQuantileDMatrix`, which bypasses CSR construction.  Since you are using distributed training on Python, I assume you will use dask for that.  There's a `DaskDeviceQuantileDMatrix` if you map the block/partition to cupy/cudf.  It will save some memory, along with a reasonable chunk size with dask one can get to less than 2x memory usage.

**Comment by trivialfis** [comment]
Closing. Right now the quantile dmatrix is the best way to reduce memory.
