### ISSUE TITLE
Pyinstaller and xgboost

### ISSUE THREAD

**Issue by marcrocasalonso** [dmlc/xgboost#7761]
Dear coders,

I am trying to launch pyinstaller for my app but it appear the commun error with xgboost and pyinstaller. I am using xgboost version 1.5.2. 
The error is :
   import xgboost as xgb
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "xgboost/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "xgboost/core.py", line 203, in <module>
  File "xgboost/core.py", line 157, in _load_lib
  File "xgboost/libpath.py", line 64, in find_lib_path
xgboost.libpath.XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path.  List of candidates:
- /tmp/_MEIHMqWQr/xgboost/lib/libxgboost.so
- /tmp/_MEIHMqWQr/xgboost/../../lib/libxgboost.so
- /tmp/_MEIHMqWQr/lib/libxgboost.so
XGBoost Python package path: /tmp/_MEIHMqWQr/xgboost
sys.prefix: /tmp/_MEIHMqWQr
See: https://xgboost.readthedocs.io/en/latest/build.html for installing XGBoost.

I have tray with adding --add-data "path" --add-data"path/VERSION" in the pyinstaller command but did not work.

Any idea about how to solve this problem?

Thanks in advance,

Kind regards,
Marc

**Comment by hcho3** [comment]
I don't think XGBoost has been tested with Pyinstaller. If anyone else can jump in and propose a fix, that would be great.

**Comment by JSalter2013** [comment]
I managed to get something similar working by doing;

**pip install pipwin**
**pipwin install xgboost**

and then something like;

**pyinstaller your.py -F --onefile --add-data "c:\repos\workspaces\.env\lib\site-packages\xgboost\xgboost.dll;xgboost" --add-data "c:\repos\workspaces\.env\Lib\site-packages\xgboost\VERSION;xgboost"**

**Comment by marcrocasalonso** [comment]
Dear JSalter2013,
I think that your solution could work for windows but not for Linux. Do you know any solution for linux ubuntu?

Thanks in advance,

**Comment by zhnnix** [comment]
@marcrocasalonso 
There are the same error for me. It bothered me for two days.

There is a solution for it. 
https://github.com/pyinstaller/pyinstaller/pull/4077/commits/a11e82681b697b36b2690ffa8365acd130b8885d

But that commit do not re-target to the https://github.com/pyinstaller/pyinstaller-hooks-contrib repo.

Temporary, 
add that hook-xgboost.py into PYTHONHOME/lib/site-package/_pyinstaller_hooks_contrib/hooks/stdhooks

then,
use your pyinstaller command,
pyinstaller --xxxx --collect-all "xgboost"

There solved my problem.

**Comment by stefanoservino** [comment]
@zhnnix I confirm that your solution resolves this problem! I got two terrible days and now it's working,

Thank you so much

**Comment by stefanoservino** [comment]
> @marcrocasalonso There are the same error for me. It bothered me for two days.
> 
> There is a solution for it. [pyinstaller/pyinstaller@a11e826](https://github.com/pyinstaller/pyinstaller/commit/a11e82681b697b36b2690ffa8365acd130b8885d)
> 
> But that commit do not re-target to the https://github.com/pyinstaller/pyinstaller-hooks-contrib repo.
> 
> Temporary, add that hook-xgboost.py into PYTHONHOME/lib/site-package/_pyinstaller_hooks_contrib/hooks/stdhooks
> 
> then, use your pyinstaller command, pyinstaller --xxxx --collect-all "xgboost"
> 
> There solved my problem.

@zhnnix I confirm that your solution resolves this problem! I got two terrible days and now it's working,

Thank you so much

N: for me works by just launch pyinstaller --onefile --noconfirm -F xxxx.py --collect-all "xgboost"

**Comment by Niclouge** [comment]
@zhnnix 
Does this solution work under linux? I didn't find the hook-xgboost.py file, which directory is this file in?
I've been stuck with this problem for days
Thank you so much!

**Comment by zhnnix** [comment]
@Niclouge 
Yes, it could work under linux.

This hook-xgboost.py file needs to be added manually. Just like [pyinstaller/pyinstaller@a11e826](https://github.com/pyinstaller/pyinstaller/commit/a11e82681b697b36b2690ffa8365acd130b8885d).

This is a temporary solution, but it can be solved immediately.

**Comment by Niclouge** [comment]
> @Niclouge Yes, it could work under linux.
> 
> This hook-xgboost.py file needs to be added manually. Just like [pyinstaller/pyinstaller@a11e826](https://github.com/pyinstaller/pyinstaller/commit/a11e82681b697b36b2690ffa8365acd130b8885d).
> 
> This is a temporary solution, but it can be solved immediately.

It really works! Super thanks !!!!!

**Comment by trivialfis** [comment]
Thank you all for the discussion. Hopefully, the thread can be helpful to others as well.

**Comment by KarenMars** [comment]
Hi，

I have followed the above solutions, and the xgboost package can be included by pyinstaller. However, I have found that some python files of xgboost have been added in the dist files. Can I convert these python files to pyd files somehow ?

**Comment by Zhejing-Chin** [comment]
Ran into the "hypothesis" module missing error when using collect_all("xgboost"). Solved by following the example of: https://pyinstaller.org/en/latest/hooks.html#PyInstaller.utils.hooks.collect_submodules 

used  `collect_all("xgboost", lambda name: 'test' not in name`) to ignore the testing submodule in xgboost instead to solve the issue.

**Comment by heon1206** [comment]
Hello, I've checked the "adding hook-xgboost.py" solution, but still having the same problem.

Is this solution still valid?
I believe the collectall method has been applied, as indicated by the output below

<used command>
-> pyinstaller --collect-all "xgboost" xgboost_test.py
<pyinstaller output:>
->1161 INFO: PyInstaller: 6.10.0, contrib hooks: 2024.8
1161 INFO: Python: 3.10.5
1361 INFO: Platform: Windows-10-10.0.18363-SP0
1362 INFO: Python environment: C:\Users\user\AppData\Local\Programs\Python\Python310
1364 INFO: wrote C:\Users\user\source\repos\varo_sweep_visualization\xgboost_test.spec
7764 INFO: Module search paths (PYTHONPATH):
['C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\pyinstaller.exe',
 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\python310.zip',
 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\DLLs',
 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib',
 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310',
 'C:\\Users\\user\\AppData\\Roaming\\Python\\Python310\\site-packages',
 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages',
 'C:\\Users\\user\\source\\repos\\varo_sweep_visualization']
pygame 2.5.2 (SDL 2.28.3, Python 3.10.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
9853 INFO: Appending 'binaries' from .spec
9854 INFO: Appending 'datas' from .spec
9871 INFO: checking Analysis
10202 INFO: Building because C:\Users\user\source\repos\varo_sweep_visualization\xgboost_test.py changed
10203 INFO: Running Analysis Analysis-00.toc
10203 INFO: Target bytecode optimization level: 0
10203 INFO: Initializing module dependency graph...
10216 INFO: Caching module graph hooks...
10302 INFO: Analyzing base_library.zip ...
14009 INFO: Processing standard module hook 'hook-heapq.py' from 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'
14156 INFO: Processing standard module hook 'hook-encodings.py' from 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'
17890 INFO: Processing standard module hook 'hook-pickle.py' from 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'
20311 INFO: Caching module dependency graph...
20585 INFO: Looking for Python shared library...
20617 INFO: Using Python shared library: C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll
20617 INFO: Analyzing C:\Users\user\source\repos\varo_sweep_visualization\xgboost_test.py
**20625 INFO: Processing standard module hook 'hook-xgboost.py' from 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'**
26355 INFO: Processing standard module hook 'hook-numpy.py' from 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\numpy\\_pyinstaller'
27425 INFO: Processing standard module hook 'hook-difflib.py' from 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'
27797 INFO: Processing standard module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'
28110 INFO: Processing standard module hook 'hook-xml.py' from 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'
29242 INFO: Processing standard module hook 'hook-platform.py' from 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'
29294 INFO: Processing standard module hook 'hook-sysconfig.py' from 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'
30091 INFO: Processing standard module hook 'hook-psutil.py' from 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\stdhooks'
32351 INFO: Processing standard module hook 'hook-scipy.py' from 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'
32417 INFO: Processing standard module hook 'hook-pytest.py' from 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\stdhooks'
32828 INFO: Processing standard module hook 'hook-py.py' from 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\stdhooks'
33154 INFO: Processing pre-safe-import-module hook 'hook-typing_extensions.py' from 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module'
33158 INFO: SetuptoolsInfo: initializing cached setuptools info...

**Comment by NIZAHO** [comment]
I would like to add that XGBOOST 1.5.1 is not good, it must be 1.5.2

**Comment by hackhaye** [comment]
> Hello, I've checked the "adding hook-xgboost.py" solution, but still having the same problem.你好，我已经检查了“adding hook-xgboost.py”解决方案，但仍然存在相同的问题。
> 
> Is this solution still valid?这个解决方案仍然有效吗？ I believe the collectall method has been applied, as indicated by the output below我相信已经应用了 collectall 方法，如下所示
> 
> used command:  使用命令： -> pyinstaller --collect-all "xgboost" xgboost_test.py
> 
> pyinstaller output:  pyinstaller 输出： ->1161 INFO: PyInstaller: 6.10.0, contrib hooks: 2024.8->1161 信息：PyInstaller：6.10.0，贡献钩子：2024.8 1161 INFO: Python: 3.10.51161 信息：Python：3.10.5 1361 INFO: Platform: Windows-10-10.0.18363-SP01361 信息：平台：Windows-10-10.0.18363-SP0 1362 INFO: Python environment: C:\Users\user\AppData\Local\Programs\Python\Python3101362 INFO: Python 环境：C:\Users\user\AppData\Local\Programs\Python\Python310 1364 INFO: wrote C:\Users\user\source\repos\varo_sweep_visualization\xgboost_test.spec1364 INFO: 已写入 C:\Users\user\source\repos\varo_sweep_visualization\xgboost_test.spec 7764 INFO: Module search paths (PYTHONPATH):7764 INFO: 模块搜索路径（PYTHONPATH）: ['C:\Users\user\AppData\Local\Programs\Python\Python310\Scripts\pyinstaller.exe', 'C:\Users\user\AppData\Local\Programs\Python\Python310\python310.zip','C:\Users\用户\AppData\Local\Programs\Python\Python310\python310.zip' 'C:\Users\user\AppData\Local\Programs\Python\Python310\DLLs','C:\Users\用户\AppData\Local\Programs\Python\Python310\DLLs' 'C:\Users\user\AppData\Local\Programs\Python\Python310\lib','C:\Users\用户\AppData\Local\Programs\Python\Python310\lib' 'C:\Users\user\AppData\Local\Programs\Python\Python310','C:\Users\用户\AppData\Local\Programs\Python\Python310' 'C:\Users\user\AppData\Roaming\Python\Python310\site-packages','C:\Users\用户\AppData\Roaming\Python\Python310\site-packages' 'C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages','C:\Users\用户\AppData\Local\Programs\Python\Python310\lib\site-packages' 'C:\Users\user\source\repos\varo_sweep_visualization']'C:\Users\用户\source\repos\varo_sweep_visualization' pygame 2.5.2 (SDL 2.28.3, Python 3.10.5) Hello from the pygame community. https://www.pygame.org/contribute.html来自 pygame 社区的问候。https://www.pygame.org/contribute.html 9853 INFO: Appending 'binaries' from .spec9853 INFO：从.spec 文件中附加'binaries' 9854 INFO: Appending 'datas' from .spec9854 INFO：从.spec 文件中附加'datas' 9871 INFO: checking Analysis9871 INFO：检查分析 10202 INFO: Building because C:\Users\user\source\repos\varo_sweep_visualization\xgboost_test.py changed10202 信息：正在构建，因为 C:\Users\user\source\repos\varo_sweep_visualization\xgboost_test.py 已更改 10203 INFO: Running Analysis Analysis-00.toc10203 信息：正在运行分析 Analysis-00.toc 10203 INFO: Target bytecode optimization level: 010203 信息：目标字节码优化级别：0 10203 INFO: Initializing module dependency graph...10203 信息：初始化模块依赖图... 10216 INFO: Caching module graph hooks...10216 信息：缓存模块图钩子... 10302 INFO: Analyzing base_library.zip ...10302 信息：分析 base_library.zip ... 14009 INFO: Processing standard module hook 'hook-heapq.py' from 'C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'14009 信息：处理标准模块钩子 'hook-heapq.py' 来自 'C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks' 14156 INFO: Processing standard module hook 'hook-encodings.py' from 'C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'14156 信息：处理标准模块钩子 'hook-encodings.py' 来自 'C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks' 17890 INFO: Processing standard module hook 'hook-pickle.py' from 'C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'17890 信息：处理标准模块钩子 'hook-pickle.py' 来自 'C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks' 20311 INFO: Caching module dependency graph...20311 信息：缓存模块依赖图... 20585 INFO: Looking for Python shared library...20585 信息：查找 Python 共享库... 20617 INFO: Using Python shared library: C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll20617 信息：使用 Python 共享库：C:\Users\user\AppData\Local\Programs\Python\Python310\python310.dll 20617 INFO: Analyzing C:\Users\user\source\repos\varo_sweep_visualization\xgboost_test.py20617 信息：分析 C:\Users\user\source\repos\varo_sweep_visualization\xgboost_test.py **20625 INFO: Processing standard module hook 'hook-xgboost.py' from 'C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'20625 信息：处理标准模块钩子 'hook-xgboost.py' 来自 'C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'**

I meet the same problem, did you solve this?

**Comment by mahirtazwar** [comment]
I am running Ubuntu 24.04.2 LTS and installed the `xgboost` package (specifically `py-xgboost=2.1.4`) in a `conda` environment. I ran into the same error and the solutions suggested above did not work for me.

I was able to get the binary working by looking for the `libxgboost.so` file in my `conda` virtual environment. In my case, it was located in `/miniconda3/envs/env_name/lib/libxgboost.so`. So, I added this binary when compiling with `pyinstaller`.

```shell
pyinstaller --noconfirm --onefile \
--add-data="./models:." \
--add-binary="/miniconda3/envs/env_name/lib/libxgboost.so:./xgboost/lib" \
--collect-all="xgboost" \
python_script.py
```

Note that I used `./xgboost/lib` as destination for the binary because the error mentioned specific lists of candidate paths where it looks for this file.

> xgboost.libpath.XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path. List of candidates:
> 
> /tmp/_MEIHMqWQr/xgboost/lib/libxgboost.so
> /tmp/_MEIHMqWQr/xgboost/../../lib/libxgboost.so
> /tmp/_MEIHMqWQr/lib/libxgboost.so

**Comment by iblacksand** [comment]
> Ran into the "hypothesis" module missing error when using collect_all("xgboost"). Solved by following the example of: https://pyinstaller.org/en/latest/hooks.html#PyInstaller.utils.hooks.collect_submodules
> 
> used `collect_all("xgboost", lambda name: 'test' not in name`) to ignore the testing submodule in xgboost instead to solve the issue.

This worked but for me, I had to specify the parameter name:

```py
datas, binaries, hiddenimports = collect_all("xgboost", filter_submodules=lambda name: 'test' not in name)
```
