### ISSUE TITLE
[JVM-packages] Training tasks schedule issue with multi-executors

### ISSUE THREAD

**Issue by nvliyuan** [dmlc/xgboost#7986]
The training tasks will be scheduled to one executor and it will hang(can be reproduced in local standalone and dataproc, but cannot be reproduced in databricks). 
Version:
spark3.1.2 standalone
xgboost4j-gpu_2.12-1.6.1.jar
xgboost4j-spark-gpu_2.12-1.6.1.jar
rapids-4-spark_2.12 2206snapshot
Config:
```
jupyter toree install    \
--spark_home=${SPARK_HOME} \
--user \
--toree_opts="--nosparkcontext"     \
--kernel_name="XGBoost4j-dmlc161"           \
--spark_opts="--master ${SPARK_MASTER_URL} \
  --jars ${PLUGIN_JAR},${XBGOOST4J_JAR},${XBGOOST4J_SPARK_JAR}      \
  --executor-cores 4 \
  --executor-memory 8G \
  --driver-memory 4G \
  --total-executor-cores 8 \
  --conf spark.plugins=com.nvidia.spark.SQLPlugin  \
  --conf spark.rapids.sql.enabled=true \
  --conf spark.locality.wait=0 \
  --conf spark.executor.resource.gpu.amount=1 \
  --conf spark.task.resource.gpu.amount=0.25 \
  --conf spark.executor.resource.gpu.discoveryScript=./getGpusResources.sh \
  --files $SPARK_HOME/examples/src/main/scripts/getGpusResources.sh"
```
Example code:
https://github.com/nvliyuan/spark-rapids-examples/blob/v2206-release/examples/XGBoost-Examples/mortgage/notebooks/scala/mortgage-gpu.ipynb

**Comment by nvliyuan** [comment]
@wbo4958 file issue here

**Comment by wbo4958** [comment]
@nvliyuan Could you provide driver and executor logs

**Comment by nvliyuan** [comment]
> 

sure, send in private due to sensitive info such as IP in log

**Comment by nvliyuan** [comment]
> @nvliyuan Could you provide driver and executor logs

sure, send in private due to sensitive info such as IP in log

**Comment by wbo4958** [comment]
Thx @nvliyuan,

The root cause is the number of Shuffle tasks is less than the num_worker, which means the shuffle task will run on part of nodes instead of all nodes. When spark tries to schedule the spark training tasks, the locality information will be the only "part of nodes" instead of all nodes, so the training task will be scheduled into part of nodes instead of all the nodes and cause this issue.

The workaround is to increase the partitions of the shuffle stage.

**Comment by nvliyuan** [comment]
@wbo4958 thanks for root cause, closed
