### ISSUE TITLE
Robust Regression Support

### ISSUE THREAD

**Issue by zhengruifeng** [dmlc/xgboost#829]
In particular, squares loss for regression models are highly sensitive to outliers, and it would be great to be able to use Robust Regression which is robust to outliers. 
In R'gbm package it is implemented as the "Laplace" distributions option.
I am interested in contributing this, if needed.

**Comment by Sandy4321** [comment]
Think globally, laplas use is weak robust, use use methods of robust
statistics

**Comment by gugatr0n1c** [comment]
MAE, huber, can be used... 

np.power(MAE, K) where K is parametr will be nice as well, we can than set K = 1.5 ie, what is nice method as well...

but is it really important? because trees are built on residuas... so if there are outliers, couple trees will take care ot them, next trees will focus on core of learning matrix... SGB is in general much more robust algorithm itself than linear regression...

there is also no clear way how to say that for example huber loss is better (if kaggle competition has cost function for leaderboard for example huber - sure, probably, but in general?)

**Comment by zhengruifeng** [comment]
@gugatr0n1c  At least, this will provide another choice...
