### ISSUE TITLE
Windows 10 64-bit error

### ISSUE THREAD

**Issue by bliger241** [dmlc/xgboost#838]
![image](https://cloud.githubusercontent.com/assets/11588153/13132189/c311fe88-d5be-11e5-87f0-ee8b50bab363.png)

I build xgboost from source and installed the module all successfully but cannot import it.  I have tried multiple times and rebuilding multiple times with the same issue.  Thanks for any help.

**Comment by andriy86** [comment]
I have the same problem.. 
![xgboost_import_error](https://cloud.githubusercontent.com/assets/17433307/13256429/ba8040a0-da18-11e5-9c4f-955942beb4f7.png)

**Comment by tqchen** [comment]
was due to current dependency on sklearn, you can install sklearn and solve this temporary

**Comment by andriy86** [comment]
Just reinstalling sklearn didn't seem to help for me. 
I had to modify the __init__ file in xgboost so that it imports from the sklearn module (Lib\site-packages\sklearn) instead of the sklearn.py file in the xgboost folder.

The following steps solved the problem:

1) Install sklearn
2) Remove sklearn.py from the main xgboost directory (Lib\site-packages\xgboost-0.4-py2.7.egg\xgboost)
3) Comment out line 12 in training.py (Lib\site-packages\xgboost-0.4-py2.7.egg\xgboost) 
#from .compat import (SKLEARN_INSTALLED, XGBStratifiedKFold, XGBKFold)

4) Update Lib\site-packages\xgboost-0.4-py2.7.egg\xgboost\__init__.py 
to 

![__init__](https://cloud.githubusercontent.com/assets/17433307/13266934/67812146-da48-11e5-936b-cea1d7809302.png)

The modified text part is shown above from line 13 - 29

try:
    #from sklearn import XGBModel, XGBClassifier, XGBRegressor
    from sklearn.base import BaseEstimator
    from sklearn.base import RegressorMixin, ClassifierMixin
    from sklearn.preprocessing import LabelEncoder
    from sklearn.cross_validation import KFold, StratifiedKFold
    SKLEARN_INSTALLED = True

    XGBKFold = KFold
    XGBStratifiedKFold = StratifiedKFold
    XGBModelBase = BaseEstimator
    XGBRegressorBase = RegressorMixin
    XGBClassifierBase = ClassifierMixin
    
    from plotting import plot_importance, plot_tree, to_graphviz
except ImportError:
    pass

**Comment by tqchen** [comment]
sounds good, can you open a PR to add these changes?
