### ISSUE TITLE
Easiest way to get version info of a XGBoost model through C++ interface

### ISSUE THREAD

**Issue by yunmengxie** [dmlc/xgboost#8435]
Hi there, I have a question regarding retrieve the version info of a XGBoost model.

Say that I have a pre-trained XGBoost model saved in bst/json format, what would be the easiest way to get the XGBoost library version that trained this model?

I checked through api methods in C++ interface, looks like these isn't an existing api to get the version info, any recommendation to achieve this?

**Comment by trivialfis** [comment]
Hi, the version recorded by XGBoost is the last version that saved the model, instead of the version that trained the model. Meaning, if you train a model with XGBoost 1.5, load the model and save it again using 1.7, then the recorded model will be changed to 1.7.

Now that this is clear, you can see the version in the output JSON file.

**Comment by trivialfis** [comment]
There's no easy way to do that with old binary format. One of the reasons for https://github.com/dmlc/xgboost/issues/7547 .
