### ISSUE TITLE
Multi-GPU single-machine on larger than memory data without Dask

### ISSUE THREAD

**Issue by sjhermanek** [dmlc/xgboost#9186]
Hi there, I'm trying to get the Python package to work on larger than memory data using GPU training. 

I'm using a data iterator with a QuantileDMatrix as shown [here](https://xgboost.readthedocs.io/en/stable/python/examples/quantile_data_iterator.html).

When I check GPU saturation using `nvidia-smi` I only see one GPU being saturated. 
Is there a way to pass in multiple GPUs without using a local Dask cluster, or alternatively use external memory and data iterator from a local Dask cluster?

Thanks for any pointers!

**Comment by trivialfis** [comment]
When multiple GPUs are used, it's by definition a distributed computing task, hence a distributed framework like dask or pyspark.

> or alternatively use external memory and data iterator from a local Dask cluster?

I don't quite understand what do you mean by this, could you please elaborate? In addition, could you please explain what you are trying to achieve?

**Comment by sjhermanek** [comment]
Thanks for the clarifying questions @trivialfis !

> I don't quite understand what do you mean by this, could you please elaborate? 
I was trying to get something like [this](https://xgboost.readthedocs.io/en/stable/python/examples/quantile_data_iterator.html) to work with Dask or another distributed framework.

> In addition, could you please explain what you are trying to achieve?
I'd like to train on larger than GPU-memory datasets using GPUs. Say, 100GB of data on a GPU with 16GB of memory.

**Comment by trivialfis** [comment]
Internally, the dask interface with QuantileDMatrix uses the iterator to go through dask data partitions similar to what the demo does.

When input is on CPU, one can squeeze some extra memory so that XGBoost might require lesser GPU memory than the actual dataset as XGBoost GPU has data compression. But that's no where near your 100/16 ratio.

Gradient boosting is not a stochastic algorithm and requires the dataset to be fully loaded into memory. Unlike deep learning where one can train the model with small batches, we can't boost a new base model using only a small fraction of data without significant lost of accuracy.

**Comment by trivialfis** [comment]
You can try external memory with gradient based sampling with a small sampling ratio, which can help. But then, it's not going to be 100/16 ratio

**Comment by sjhermanek** [comment]
I understand, thank you for the guidance @trivialfis !
