### ISSUE TITLE
XGBClassifier doesn't fully match the sklearn interface

### ISSUE THREAD

**Issue by DSantiagoBC** [dmlc/xgboost#9502]
Estimators in sklearn accept the `verbose` parameter to define the level of messages to be logged, but in `XGBClassifier` this parameter is called `verbosity` instead. This makes necessary to check for the specific type of `XGBClassifier` when defining a list of estimators to initialize and compare.

Related to this, estimators capable of multithreaded processing use by default a single thread, and setting `n_jobs=-1` allows the usage of all available processors, but this isn't the case for `XGBClassifier` which uses all processors by default.

**Comment by trivialfis** [comment]
yeah, it's a dilemma for us. On the one hand, we want to keep some consistency within XGBoost. It would be weird if a user get a different set of parameters when switching from sklearn interface to the native interface or to the spark interface. On the other hand, we want to match some of the conventions in the ecosystem.

I think the two parameters you mentioned `n_jobs` and `verbosity` are fine. Just set the `n_jobs` explicitly. The default `verbosity` is warnings only, which should be addressed instead of suppressed.

**Comment by trivialfis** [comment]
Feel free to reopen if you find other inconsistencies that are required by the estimator guidelines
