### ISSUE TITLE
Inconsistent warning in XGBClassifier and XGBRegressor (scikit-learn api).

### ISSUE THREAD

**Issue by chulwoohan** [dmlc/xgboost#9594]
I made a simple code to understand the behavior of xgboost better. In the code below, I don't get any warning message when I call the fit function, whereas the following warning message is raised when the predict function is called. I understand that the warning is raised because the data is in cpu while the device is set to 'cuda'. What I don't understand is why no warning is issued in the fit function. I also wonder what would be the best practice to suppress the warning.

********** warning message *************
Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.
This warning will only be shown once.
  warnings.warn(smsg, UserWarning)

********** code *************
from xgboost import XGBClassifier, XGBRegressor
import numpy as np

X = np.random.random([1000, 3])
y = np.random.randint(0, 3, [1000])

xgbc = XGBClassifier(device='cuda')
xgbc.fit(X, y)
y_pre = xgbc.predict(X)

**Comment by trivialfis** [comment]
We raised the warning for prediction but not fit. Most of the time, users expect lower latency for prediction, especially with repeated calls, either for real inference or for evaluation during training. On the other hand, it's fine to have a longer preparation time for fit since fit usually takes a much longer time and is called only once in each training session.

To suppress the warning, you can:
- use `cupy` or `cudf` as input types to match the `device=cuda`.
- use `device=cpu` with cpu input types like numpy and pandas.
- set `verbosity=0`.

**Comment by trivialfis** [comment]
Feel free to close if this answers your question, or if you have suggested changes that can improve the feedback.

**Comment by chulwoohan** [comment]
Thank you for the quick reply. I tested cupy by changing the above example as below.

xgbc = XGBClassifier(device='cuda')
xgbc.fit(X, y)
X2 = cupy.array(X)
y_pre = xgbc.predict(X2)

It works fine but takes a longer time: changing to cupy array and predicting both take longer than just predicting using X. Am I correct in assuming that I can benefit from cupy only when the size of X is sufficiently large?

**Comment by trivialfis** [comment]
Yes, GPU works better with batch data
