### ISSUE TITLE
Documentation needed for QuantileDMatrix

### ISSUE THREAD

**Issue by phydev** [dmlc/xgboost#9680]
The mathematical definition of the transformation performed inside QuantileDMatrix and the expected behaviour are not documented anywhere. When I tried to infer what was happening inside this function by testing simple cases I got strange results, please see the discussion: https://discuss.xgboost.ai/t/what-is-the-mathematical-definition-of-the-quantile-transformation-in-xgboost-quantiledmatrix/3366

**Comment by trivialfis** [comment]
Hi, you are correct that we have a custom min value in the quantile DMatrix, @hcho3 gave an explanation here: https://github.com/dmlc/xgboost/issues/2914#issuecomment-348388114

I want to replace it with a different bin searching strategy, but so far haven't been able to prioritize it yet.

**Comment by phydev** [comment]
Hi, thanks for taking time to reply, but I can't quite grasp how the issue you have linked is related with the behaviour of `QuantileDMatrix`, other than saying that this is another arbitrary algorithmic choice.

From a statistical point of view it seems a strange choice to replace data entries by arbitrary minimum values - why the minimum cannot remain the same as it is in the original data? From the best of my understanding, if `max_bin` is greater or equal to the number of samples, no transformation should be applied to the data since the quantile transformation would be the median of single observations. This would be a more consistent and clear behaviour for this function. In any case, since this is a non-parametric method changing the minimum for each feature should not impact the final model anyway. 

Thank you for all your effort on the development of XGBoost and for providing support to the community.

**Comment by hcho3** [comment]
In `QuantileDMatrix`, `min(2x, 0)-1.e-05` is being used as a surrogate for `-inf`. There is no statistical justification for this choice, other than the fact that this value is chosen to be smaller than all observed values of the feature `x`.

> no transformation should be applied to the data since the quantile transformation would be the median of single observations

Each data point is actually replaced with the lower bound of each quantile bin. For the smallest bin, the lower bound is `-inf`. But instead of `-inf`, we use `min(2x, 0)-1.e-05` instead. As I noted in #2914, `min(2x, 0)-1.e-05` is not really a good surrogate for `-inf`. We should use `-inf` directly.

**Comment by phydev** [comment]
Thanks @hcho3 and @trivialfis, this is clear to me now. Have a nice day!
