### ISSUE TITLE
Gblinear vs GbTree

### ISSUE THREAD

**Issue by pawelgodula** [dmlc/xgboost#981]
This is a question, not an issue.

What is the precise difference between gbtree and gblinear boosters? Some article will suffice.

Thanks so much

**Comment by khotilov** [comment]
Boosting is an ensemble meta-algorithm that iteratively trains sequences of weaker base learners. 
- gbtree booster uses version of regression tree as a weak learner
- gblinear uses (generalized) linear regression with l1&l2 shrinkage. But since it's an additive process, and since linear regression is an additive model itself, only the combined linear model coefficients are retained. Also see #332.
