### ISSUE TITLE
[R] Checking whether DMatrix has field implies making full data copies of said field

### ISSUE THREAD

**Issue by david-cortes** [dmlc/xgboost#9865]
Follow up from https://github.com/dmlc/xgboost/pull/9863
ref https://github.com/dmlc/xgboost/issues/9810

In methods such as `print.xgb.DMatrix`:
https://github.com/dmlc/xgboost/blob/562352101d5dd1630eded1522b9b4ed9b07e8692/R-package/R/xgb.DMatrix.R#L517

The code checks whether a DMatrix has a given field by retrieving it.

This causes a full (maybe even two?) data copy of the underlying field being retrieved, but the data there is not used: it's only being checked that it exists.

Would be more efficient to use some way of checking that the DMatrix has a field taht would not involve copying all of the data in that field.

**Comment by trivialfis** [comment]
We don't have this method yet. For the print method you referenced, I think it's easy to just get all meta info and filter it by null values. We need all the available fields anyway.

As for the AFT PR, I think we can merge it for now, but wouldn't it be better for the long term that we can avoid processing the `DMatrix` and move toward the high-level interface? If so, we can just get the label/bounds from user inputs instead of the DMatrix.
