### ISSUE TITLE
slower training from vector-leaf models when it should be faster

### ISSUE THREAD

**Issue by AlexiaJM** [dmlc/xgboost#9870]
Currently, training a vector-leaf model is slower than training a one-model-per-target model. I'm not sure how this is possible. 

Let say you have 50 outputs with regression, then a vector-leaf model should try to find the data split such that the average loss (over the 50 losses, one loss for each output) is minimized. Since calculating the average loss is fast and you are making a single model, this should be close to 50 times faster than training 50 models (one for each output). Why is this not the case? Is there a way to actually get a speedup?

Example:
```
import xgboost as xgb
import numpy as np
X = np.random.normal(size=(1000, 50))
y = np.random.normal(size=(1000, 50))
data = xgb.QuantileDMatrix(data=X, label=y)

# 4.41 seconds
xgb_dict = {'objective': 'reg:squarederror', "tree_method": 'hist', 'device': 'cpu'}
out = xgb.train(xgb_dict, data, num_boost_round=10)

# 6.81 seconds
xgb_dict = {'objective': 'reg:squarederror', "tree_method": 'hist', 'device': 'cpu', 'multi_strategy': "multi_output_tree"}
out = xgb.train(xgb_dict, data, num_boost_round=10)
```

**Comment by trivialfis** [comment]
There are several potential causes of the slowdown. With a single model, XGBoost is likely to grow a larger model, for a tree model, the number of leaves can be exponential with the depth of the tree, which drives the number of histograms being built to be exponential. Then the vector leaf implementation is not yet well optimized since it's still a work in progress. Lastly, training speed is not the primary objective for having vector leaves, we have some other optimizations being planed for large number of targets.
