### ISSUE TITLE
PLEASE UPDATE PYTHON-PACKAGE UNDER PyPI

### ISSUE THREAD

**Issue by nicoJiang** [dmlc/xgboost#989]
There have been several helpful and functional updates during the python-package.However,the pip version is just a little out-of-date.
For instance,I have been eager for the implementation of FEATURE_IMPORTANCE for a long time but I can only copy the relevant codes from /python-package/xgboost/sklearn.py and manually update the local xgboost-lib.

**Comment by phunterlau** [comment]
will do it when I get back, and there will be a wheels installation too, hopefully

**Comment by bryan-woods** [comment]
This would be very helpful. I'm eagerly awaiting an update as it would make my life much easier.

**Comment by phunterlau** [comment]
@bryan-woods some progress and thoughts: the old PyPI installation builds source from scratch which might not be a good idea for the current xgboost structure, since cmake and openMP support can cause problems on different platforms, e.g. Mac's system `clang` OpenMP issue, cmake's `ar` issues on Mac etc, so I am experimenting an `wheels-only` solution with static link pre-compiled lib for major platforms, and stop supporting the old PyPI installation from scratch. It would be a good chance to include windows platform pre-compiled libs, if we can have some one maintaining the windows binary package.

**Comment by mlehl88** [comment]
@phunterlau Thank you for your contribution of this implementation! Did you happen to make any progress on re-publishing it on PyPi (or similar)? I am currently using the PyPi installation in a project and an update on PyPi would be an easy fix to some issues I have.
